/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50141
Source Host           : localhost:3306
Source Database       : swap_nutrition

Target Server Type    : MYSQL
Target Server Version : 50141
File Encoding         : 65001

Date: 2010-12-07 09:47:01
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `a_languages_a_product_types`
-- ----------------------------
DROP TABLE IF EXISTS `a_languages_a_product_types`;
CREATE TABLE `a_languages_a_product_types` (
  `id` smallint(3) unsigned NOT NULL AUTO_INCREMENT,
  `a_language_id` tinyint(1) unsigned NOT NULL,
  `a_product_type_id` smallint(5) unsigned NOT NULL,
  `name` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1016 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of a_languages_a_product_types
-- ----------------------------
INSERT INTO `a_languages_a_product_types` VALUES ('1', '1', '1', 'Butter');
INSERT INTO `a_languages_a_product_types` VALUES ('2', '1', '2', 'Butter oil');
INSERT INTO `a_languages_a_product_types` VALUES ('3', '1', '3', 'Cheese');
INSERT INTO `a_languages_a_product_types` VALUES ('4', '1', '4', 'Cheese food');
INSERT INTO `a_languages_a_product_types` VALUES ('5', '1', '5', 'Cheese spread');
INSERT INTO `a_languages_a_product_types` VALUES ('6', '1', '6', 'Cream');
INSERT INTO `a_languages_a_product_types` VALUES ('7', '1', '7', 'Eggnog');
INSERT INTO `a_languages_a_product_types` VALUES ('8', '1', '8', 'Sour dressing');
INSERT INTO `a_languages_a_product_types` VALUES ('9', '1', '9', 'Milk');
INSERT INTO `a_languages_a_product_types` VALUES ('10', '1', '10', 'Cream substitute');
INSERT INTO `a_languages_a_product_types` VALUES ('11', '1', '11', 'Dessert topping');
INSERT INTO `a_languages_a_product_types` VALUES ('12', '1', '12', 'Sour cream');
INSERT INTO `a_languages_a_product_types` VALUES ('13', '1', '13', 'Milk substitutes');
INSERT INTO `a_languages_a_product_types` VALUES ('14', '1', '14', 'Milk shakes');
INSERT INTO `a_languages_a_product_types` VALUES ('15', '1', '15', 'Whey');
INSERT INTO `a_languages_a_product_types` VALUES ('16', '1', '16', 'Yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('17', '1', '17', 'Egg');
INSERT INTO `a_languages_a_product_types` VALUES ('18', '1', '18', 'Egg substitute');
INSERT INTO `a_languages_a_product_types` VALUES ('19', '1', '19', 'Cheese substitute');
INSERT INTO `a_languages_a_product_types` VALUES ('20', '1', '20', 'Cheese fondue');
INSERT INTO `a_languages_a_product_types` VALUES ('21', '1', '21', 'Cheese sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('22', '1', '22', 'USDA Commodity');
INSERT INTO `a_languages_a_product_types` VALUES ('23', '1', '23', 'Parmesan cheese topping');
INSERT INTO `a_languages_a_product_types` VALUES ('24', '1', '24', 'KRAFT CHEEZ WHIZ Pasteurized P');
INSERT INTO `a_languages_a_product_types` VALUES ('25', '1', '25', 'KRAFT CHEEZ WHIZ LIGHT Pasteur');
INSERT INTO `a_languages_a_product_types` VALUES ('26', '1', '26', 'KRAFT FREE Singles American No');
INSERT INTO `a_languages_a_product_types` VALUES ('27', '1', '27', 'KRAFT VELVEETA Pasteurized Pro');
INSERT INTO `a_languages_a_product_types` VALUES ('28', '1', '28', 'KRAFT VELVEETA LIGHT Reduced F');
INSERT INTO `a_languages_a_product_types` VALUES ('29', '1', '29', 'KRAFT BREAKSTONE\'S Reduced Fat');
INSERT INTO `a_languages_a_product_types` VALUES ('30', '1', '30', 'KRAFT BREAKSTONE\'S FREE Fat Fr');
INSERT INTO `a_languages_a_product_types` VALUES ('31', '1', '31', 'KRAFT BREYERS Lowfat Strawberr');
INSERT INTO `a_languages_a_product_types` VALUES ('32', '1', '32', 'KRAFT BREYERS LIGHT N\' LIVELY ');
INSERT INTO `a_languages_a_product_types` VALUES ('33', '1', '33', 'KRAFT BREYERS Smooth & Creamy ');
INSERT INTO `a_languages_a_product_types` VALUES ('34', '1', '34', 'KRAFT BREYERS LIGHT Nonfat Str');
INSERT INTO `a_languages_a_product_types` VALUES ('35', '1', '35', 'Reddi Wip Fat Free Whipped Top');
INSERT INTO `a_languages_a_product_types` VALUES ('36', '1', '36', 'Egg Mix');
INSERT INTO `a_languages_a_product_types` VALUES ('37', '1', '37', 'Cheese product');
INSERT INTO `a_languages_a_product_types` VALUES ('38', '1', '38', 'Protein supplement');
INSERT INTO `a_languages_a_product_types` VALUES ('39', '1', '39', 'Dulce de Leche');
INSERT INTO `a_languages_a_product_types` VALUES ('40', '1', '40', 'Spices');
INSERT INTO `a_languages_a_product_types` VALUES ('41', '1', '41', 'Basil');
INSERT INTO `a_languages_a_product_types` VALUES ('42', '1', '42', 'Dill weed');
INSERT INTO `a_languages_a_product_types` VALUES ('43', '1', '43', 'Mustard');
INSERT INTO `a_languages_a_product_types` VALUES ('44', '1', '44', 'Salt');
INSERT INTO `a_languages_a_product_types` VALUES ('45', '1', '45', 'Vinegar');
INSERT INTO `a_languages_a_product_types` VALUES ('46', '1', '46', 'Thyme');
INSERT INTO `a_languages_a_product_types` VALUES ('47', '1', '47', 'Vanilla extract');
INSERT INTO `a_languages_a_product_types` VALUES ('48', '1', '48', 'Capers');
INSERT INTO `a_languages_a_product_types` VALUES ('49', '1', '49', 'Horseradish');
INSERT INTO `a_languages_a_product_types` VALUES ('50', '1', '50', 'Rosemary');
INSERT INTO `a_languages_a_product_types` VALUES ('51', '1', '51', 'Peppermint');
INSERT INTO `a_languages_a_product_types` VALUES ('52', '1', '52', 'Spearmint');
INSERT INTO `a_languages_a_product_types` VALUES ('53', '1', '53', 'CAMPBELL Soup Company');
INSERT INTO `a_languages_a_product_types` VALUES ('54', '1', '54', 'Babyfood');
INSERT INTO `a_languages_a_product_types` VALUES ('55', '1', '55', 'Gerber graduates Fruit Strips ');
INSERT INTO `a_languages_a_product_types` VALUES ('56', '1', '56', 'Zwieback');
INSERT INTO `a_languages_a_product_types` VALUES ('57', '1', '57', 'Infant formula');
INSERT INTO `a_languages_a_product_types` VALUES ('58', '1', '58', 'Child formula');
INSERT INTO `a_languages_a_product_types` VALUES ('59', '1', '59', 'Baby food');
INSERT INTO `a_languages_a_product_types` VALUES ('60', '1', '60', 'Fat');
INSERT INTO `a_languages_a_product_types` VALUES ('61', '1', '61', 'Lard');
INSERT INTO `a_languages_a_product_types` VALUES ('62', '1', '62', 'Salad dressing');
INSERT INTO `a_languages_a_product_types` VALUES ('63', '1', '63', 'Sandwich spread');
INSERT INTO `a_languages_a_product_types` VALUES ('64', '1', '64', 'Shortening');
INSERT INTO `a_languages_a_product_types` VALUES ('65', '1', '65', 'Oil');
INSERT INTO `a_languages_a_product_types` VALUES ('66', '1', '66', 'Margarine');
INSERT INTO `a_languages_a_product_types` VALUES ('67', '1', '67', 'Margarine-like');
INSERT INTO `a_languages_a_product_types` VALUES ('68', '1', '68', 'Vegetable oil');
INSERT INTO `a_languages_a_product_types` VALUES ('69', '1', '69', 'Shortening bread');
INSERT INTO `a_languages_a_product_types` VALUES ('70', '1', '70', 'Shortening cake mix');
INSERT INTO `a_languages_a_product_types` VALUES ('71', '1', '71', 'Shortening industrial');
INSERT INTO `a_languages_a_product_types` VALUES ('72', '1', '72', 'Shortening frying (heavy duty)');
INSERT INTO `a_languages_a_product_types` VALUES ('73', '1', '73', 'Shortening confectionery');
INSERT INTO `a_languages_a_product_types` VALUES ('74', '1', '74', 'Shortening household soybean (');
INSERT INTO `a_languages_a_product_types` VALUES ('75', '1', '75', 'Fish oil');
INSERT INTO `a_languages_a_product_types` VALUES ('76', '1', '76', 'Meat drippings (lard');
INSERT INTO `a_languages_a_product_types` VALUES ('77', '1', '77', 'Animal fat');
INSERT INTO `a_languages_a_product_types` VALUES ('78', '1', '78', 'Margarine-like spread with yog');
INSERT INTO `a_languages_a_product_types` VALUES ('79', '1', '79', 'Margarine-like spread with yog');
INSERT INTO `a_languages_a_product_types` VALUES ('80', '1', '80', 'Margarine Spread');
INSERT INTO `a_languages_a_product_types` VALUES ('81', '1', '81', 'Margarine-like shortening');
INSERT INTO `a_languages_a_product_types` VALUES ('82', '1', '82', 'USDA Commodity Food');
INSERT INTO `a_languages_a_product_types` VALUES ('83', '1', '83', 'Margarine-like spread');
INSERT INTO `a_languages_a_product_types` VALUES ('84', '1', '84', 'Margarine-like vegetable-oil s');
INSERT INTO `a_languages_a_product_types` VALUES ('85', '1', '85', 'Chicken');
INSERT INTO `a_languages_a_product_types` VALUES ('86', '1', '86', 'Duck');
INSERT INTO `a_languages_a_product_types` VALUES ('87', '1', '87', 'Goose');
INSERT INTO `a_languages_a_product_types` VALUES ('88', '1', '88', 'Guinea hen');
INSERT INTO `a_languages_a_product_types` VALUES ('89', '1', '89', 'Pheasant');
INSERT INTO `a_languages_a_product_types` VALUES ('90', '1', '90', 'Quail');
INSERT INTO `a_languages_a_product_types` VALUES ('91', '1', '91', 'Squab');
INSERT INTO `a_languages_a_product_types` VALUES ('92', '1', '92', 'Turkey');
INSERT INTO `a_languages_a_product_types` VALUES ('93', '1', '93', 'Pate de foie gras');
INSERT INTO `a_languages_a_product_types` VALUES ('94', '1', '94', 'Turkey and gravy');
INSERT INTO `a_languages_a_product_types` VALUES ('95', '1', '95', 'Turkey patties');
INSERT INTO `a_languages_a_product_types` VALUES ('96', '1', '96', 'Turkey breast');
INSERT INTO `a_languages_a_product_types` VALUES ('97', '1', '97', 'Turkey thigh');
INSERT INTO `a_languages_a_product_types` VALUES ('98', '1', '98', 'Turkey roast');
INSERT INTO `a_languages_a_product_types` VALUES ('99', '1', '99', 'Turkey sticks');
INSERT INTO `a_languages_a_product_types` VALUES ('100', '1', '100', 'Poultry');
INSERT INTO `a_languages_a_product_types` VALUES ('101', '1', '101', 'Poultry food products');
INSERT INTO `a_languages_a_product_types` VALUES ('102', '1', '102', 'Chicken nuggets');
INSERT INTO `a_languages_a_product_types` VALUES ('103', '1', '103', 'Chicken patty');
INSERT INTO `a_languages_a_product_types` VALUES ('104', '1', '104', 'Chicken breast tenders');
INSERT INTO `a_languages_a_product_types` VALUES ('105', '1', '105', 'USDA Commodity Chicken');
INSERT INTO `a_languages_a_product_types` VALUES ('106', '1', '106', 'Emu');
INSERT INTO `a_languages_a_product_types` VALUES ('107', '1', '107', 'Ostrich');
INSERT INTO `a_languages_a_product_types` VALUES ('108', '1', '108', 'Ground Turkey');
INSERT INTO `a_languages_a_product_types` VALUES ('109', '1', '109', 'Soup');
INSERT INTO `a_languages_a_product_types` VALUES ('110', '1', '110', 'Sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('111', '1', '111', 'Gravy');
INSERT INTO `a_languages_a_product_types` VALUES ('112', '1', '112', 'Split pea soup');
INSERT INTO `a_languages_a_product_types` VALUES ('113', '1', '113', 'Split pea with ham soup');
INSERT INTO `a_languages_a_product_types` VALUES ('114', '1', '114', 'Fish broth');
INSERT INTO `a_languages_a_product_types` VALUES ('115', '1', '115', 'Potato soup');
INSERT INTO `a_languages_a_product_types` VALUES ('116', '1', '116', 'Adobo fresco');
INSERT INTO `a_languages_a_product_types` VALUES ('117', '1', '117', 'Barbecue loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('118', '1', '118', 'Beerwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('119', '1', '119', 'Sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('120', '1', '120', 'Blood sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('121', '1', '121', 'Bockwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('122', '1', '122', 'Bologna');
INSERT INTO `a_languages_a_product_types` VALUES ('123', '1', '123', 'Bratwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('124', '1', '124', 'Braunschweiger (a liver sausag');
INSERT INTO `a_languages_a_product_types` VALUES ('125', '1', '125', 'Brotwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('126', '1', '126', 'Cheesefurter');
INSERT INTO `a_languages_a_product_types` VALUES ('127', '1', '127', 'Chicken roll');
INSERT INTO `a_languages_a_product_types` VALUES ('128', '1', '128', 'Chicken spread');
INSERT INTO `a_languages_a_product_types` VALUES ('129', '1', '129', 'Chorizo');
INSERT INTO `a_languages_a_product_types` VALUES ('130', '1', '130', 'Corned beef loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('131', '1', '131', 'Dutch brand loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('132', '1', '132', 'Frankfurter');
INSERT INTO `a_languages_a_product_types` VALUES ('133', '1', '133', 'Ham');
INSERT INTO `a_languages_a_product_types` VALUES ('134', '1', '134', 'Ham salad spread');
INSERT INTO `a_languages_a_product_types` VALUES ('135', '1', '135', 'Ham and cheese loaf or roll');
INSERT INTO `a_languages_a_product_types` VALUES ('136', '1', '136', 'Ham and cheese spread');
INSERT INTO `a_languages_a_product_types` VALUES ('137', '1', '137', 'Headcheese');
INSERT INTO `a_languages_a_product_types` VALUES ('138', '1', '138', 'Honey loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('139', '1', '139', 'Kielbasa');
INSERT INTO `a_languages_a_product_types` VALUES ('140', '1', '140', 'Knackwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('141', '1', '141', 'Lebanon bologna');
INSERT INTO `a_languages_a_product_types` VALUES ('142', '1', '142', 'Liver cheese');
INSERT INTO `a_languages_a_product_types` VALUES ('143', '1', '143', 'Liver sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('144', '1', '144', 'Luncheon meat');
INSERT INTO `a_languages_a_product_types` VALUES ('145', '1', '145', 'Mortadella');
INSERT INTO `a_languages_a_product_types` VALUES ('146', '1', '146', 'Olive loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('147', '1', '147', 'Pastrami');
INSERT INTO `a_languages_a_product_types` VALUES ('148', '1', '148', 'Pate');
INSERT INTO `a_languages_a_product_types` VALUES ('149', '1', '149', 'Peppered loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('150', '1', '150', 'Pepperoni');
INSERT INTO `a_languages_a_product_types` VALUES ('151', '1', '151', 'Pickle and pimiento loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('152', '1', '152', 'Polish sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('153', '1', '153', 'Luxury loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('154', '1', '154', 'Mother\'s loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('155', '1', '155', 'Picnic loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('156', '1', '156', 'Pork sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('157', '1', '157', 'Pork and beef sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('158', '1', '158', 'Turkey sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('159', '1', '159', 'Poultry salad sandwich spread');
INSERT INTO `a_languages_a_product_types` VALUES ('160', '1', '160', 'Salami');
INSERT INTO `a_languages_a_product_types` VALUES ('161', '1', '161', 'Smoked link sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('162', '1', '162', 'Thuringer');
INSERT INTO `a_languages_a_product_types` VALUES ('163', '1', '163', 'Turkey breast meat');
INSERT INTO `a_languages_a_product_types` VALUES ('164', '1', '164', 'Turkey ham');
INSERT INTO `a_languages_a_product_types` VALUES ('165', '1', '165', 'Turkey roll');
INSERT INTO `a_languages_a_product_types` VALUES ('166', '1', '166', 'Honey roll sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('167', '1', '167', 'Luncheon sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('168', '1', '168', 'New england brand sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('169', '1', '169', 'OSCAR MAYER');
INSERT INTO `a_languages_a_product_types` VALUES ('170', '1', '170', 'OSCAR MAYER. Bologna (Wisconsi');
INSERT INTO `a_languages_a_product_types` VALUES ('171', '1', '171', 'LOUIS RICH');
INSERT INTO `a_languages_a_product_types` VALUES ('172', '1', '172', 'BUTCHER BOY MEATS');
INSERT INTO `a_languages_a_product_types` VALUES ('173', '1', '173', 'CARL BUDDIG');
INSERT INTO `a_languages_a_product_types` VALUES ('174', '1', '174', 'CARL BUDDIG. Cooked Smoked Bee');
INSERT INTO `a_languages_a_product_types` VALUES ('175', '1', '175', 'HORMEL SPAM');
INSERT INTO `a_languages_a_product_types` VALUES ('176', '1', '176', 'HORMEL Pillow Pak Sliced Turke');
INSERT INTO `a_languages_a_product_types` VALUES ('177', '1', '177', 'HORMEL WRANGLER Beef Franks');
INSERT INTO `a_languages_a_product_types` VALUES ('178', '1', '178', 'Liverwurst spread');
INSERT INTO `a_languages_a_product_types` VALUES ('179', '1', '179', 'Roast beef spread');
INSERT INTO `a_languages_a_product_types` VALUES ('180', '1', '180', 'Swisswurst');
INSERT INTO `a_languages_a_product_types` VALUES ('181', '1', '181', 'Bacon and beef sticks');
INSERT INTO `a_languages_a_product_types` VALUES ('182', '1', '182', 'Yachtwurst');
INSERT INTO `a_languages_a_product_types` VALUES ('183', '1', '183', 'Chicken breast');
INSERT INTO `a_languages_a_product_types` VALUES ('184', '1', '184', 'Oven-roasted chicken breast ro');
INSERT INTO `a_languages_a_product_types` VALUES ('185', '1', '185', 'Macaroni and cheese loaf');
INSERT INTO `a_languages_a_product_types` VALUES ('186', '1', '186', 'Scrapple');
INSERT INTO `a_languages_a_product_types` VALUES ('187', '1', '187', 'Beef sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('188', '1', '188', 'Pork and turkey sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('189', '1', '189', 'Cereals ready-to-eat');
INSERT INTO `a_languages_a_product_types` VALUES ('190', '1', '190', 'Cereals');
INSERT INTO `a_languages_a_product_types` VALUES ('191', '1', '191', 'Cereals ready to eat');
INSERT INTO `a_languages_a_product_types` VALUES ('192', '1', '192', 'Milk and cereal bar');
INSERT INTO `a_languages_a_product_types` VALUES ('193', '1', '193', 'Rice and Wheat cereal bar');
INSERT INTO `a_languages_a_product_types` VALUES ('194', '1', '194', 'Cereal wafer straws');
INSERT INTO `a_languages_a_product_types` VALUES ('195', '1', '195', 'Incaparina');
INSERT INTO `a_languages_a_product_types` VALUES ('196', '1', '196', 'KASHI GOLEAN Crisp Toasted Ber');
INSERT INTO `a_languages_a_product_types` VALUES ('197', '1', '197', 'Acerola');
INSERT INTO `a_languages_a_product_types` VALUES ('198', '1', '198', 'Acerola juice');
INSERT INTO `a_languages_a_product_types` VALUES ('199', '1', '199', 'Apples');
INSERT INTO `a_languages_a_product_types` VALUES ('200', '1', '200', 'Apple juice');
INSERT INTO `a_languages_a_product_types` VALUES ('201', '1', '201', 'Applesauce');
INSERT INTO `a_languages_a_product_types` VALUES ('202', '1', '202', 'Apricots');
INSERT INTO `a_languages_a_product_types` VALUES ('203', '1', '203', 'Apricot nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('204', '1', '204', 'Avocados');
INSERT INTO `a_languages_a_product_types` VALUES ('205', '1', '205', 'Bananas');
INSERT INTO `a_languages_a_product_types` VALUES ('206', '1', '206', 'Blackberries');
INSERT INTO `a_languages_a_product_types` VALUES ('207', '1', '207', 'Blackberry juice');
INSERT INTO `a_languages_a_product_types` VALUES ('208', '1', '208', 'Blueberries');
INSERT INTO `a_languages_a_product_types` VALUES ('209', '1', '209', 'Boysenberries');
INSERT INTO `a_languages_a_product_types` VALUES ('210', '1', '210', 'Breadfruit');
INSERT INTO `a_languages_a_product_types` VALUES ('211', '1', '211', 'Carambola');
INSERT INTO `a_languages_a_product_types` VALUES ('212', '1', '212', 'Carissa');
INSERT INTO `a_languages_a_product_types` VALUES ('213', '1', '213', 'Cherimoya');
INSERT INTO `a_languages_a_product_types` VALUES ('214', '1', '214', 'Cherries');
INSERT INTO `a_languages_a_product_types` VALUES ('215', '1', '215', 'Crabapples');
INSERT INTO `a_languages_a_product_types` VALUES ('216', '1', '216', 'Cranberries');
INSERT INTO `a_languages_a_product_types` VALUES ('217', '1', '217', 'Cranberry sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('218', '1', '218', 'Cranberry-orange relish');
INSERT INTO `a_languages_a_product_types` VALUES ('219', '1', '219', 'Currants');
INSERT INTO `a_languages_a_product_types` VALUES ('220', '1', '220', 'Custard-apple');
INSERT INTO `a_languages_a_product_types` VALUES ('221', '1', '221', 'Dates');
INSERT INTO `a_languages_a_product_types` VALUES ('222', '1', '222', 'Elderberries');
INSERT INTO `a_languages_a_product_types` VALUES ('223', '1', '223', 'Figs');
INSERT INTO `a_languages_a_product_types` VALUES ('224', '1', '224', 'Fruit cocktail');
INSERT INTO `a_languages_a_product_types` VALUES ('225', '1', '225', 'Fruit salad');
INSERT INTO `a_languages_a_product_types` VALUES ('226', '1', '226', 'Gooseberries');
INSERT INTO `a_languages_a_product_types` VALUES ('227', '1', '227', 'Grapefruit');
INSERT INTO `a_languages_a_product_types` VALUES ('228', '1', '228', 'Grapefruit juice');
INSERT INTO `a_languages_a_product_types` VALUES ('229', '1', '229', 'Grapes');
INSERT INTO `a_languages_a_product_types` VALUES ('230', '1', '230', 'Grape juice');
INSERT INTO `a_languages_a_product_types` VALUES ('231', '1', '231', 'Grape juice cocktail');
INSERT INTO `a_languages_a_product_types` VALUES ('232', '1', '232', 'Groundcherries');
INSERT INTO `a_languages_a_product_types` VALUES ('233', '1', '233', 'Guavas');
INSERT INTO `a_languages_a_product_types` VALUES ('234', '1', '234', 'Guava sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('235', '1', '235', 'Jackfruit');
INSERT INTO `a_languages_a_product_types` VALUES ('236', '1', '236', 'Java-plum');
INSERT INTO `a_languages_a_product_types` VALUES ('237', '1', '237', 'Jujube');
INSERT INTO `a_languages_a_product_types` VALUES ('238', '1', '238', 'Kiwifruit');
INSERT INTO `a_languages_a_product_types` VALUES ('239', '1', '239', 'Kumquats');
INSERT INTO `a_languages_a_product_types` VALUES ('240', '1', '240', 'Lemons');
INSERT INTO `a_languages_a_product_types` VALUES ('241', '1', '241', 'Lemon juice');
INSERT INTO `a_languages_a_product_types` VALUES ('242', '1', '242', 'Lemon peel');
INSERT INTO `a_languages_a_product_types` VALUES ('243', '1', '243', 'Limes');
INSERT INTO `a_languages_a_product_types` VALUES ('244', '1', '244', 'Lime juice');
INSERT INTO `a_languages_a_product_types` VALUES ('245', '1', '245', 'Litchis');
INSERT INTO `a_languages_a_product_types` VALUES ('246', '1', '246', 'Loganberries');
INSERT INTO `a_languages_a_product_types` VALUES ('247', '1', '247', 'Longans');
INSERT INTO `a_languages_a_product_types` VALUES ('248', '1', '248', 'Loquats');
INSERT INTO `a_languages_a_product_types` VALUES ('249', '1', '249', 'Mammy-apple');
INSERT INTO `a_languages_a_product_types` VALUES ('250', '1', '250', 'Mangos');
INSERT INTO `a_languages_a_product_types` VALUES ('251', '1', '251', 'Mangosteen');
INSERT INTO `a_languages_a_product_types` VALUES ('252', '1', '252', 'Melons');
INSERT INTO `a_languages_a_product_types` VALUES ('253', '1', '253', 'Melon balls');
INSERT INTO `a_languages_a_product_types` VALUES ('254', '1', '254', 'Fruit');
INSERT INTO `a_languages_a_product_types` VALUES ('255', '1', '255', 'Mulberries');
INSERT INTO `a_languages_a_product_types` VALUES ('256', '1', '256', 'Nectarines');
INSERT INTO `a_languages_a_product_types` VALUES ('257', '1', '257', 'Oheloberries');
INSERT INTO `a_languages_a_product_types` VALUES ('258', '1', '258', 'Olives');
INSERT INTO `a_languages_a_product_types` VALUES ('259', '1', '259', 'Oranges');
INSERT INTO `a_languages_a_product_types` VALUES ('260', '1', '260', 'Orange juice');
INSERT INTO `a_languages_a_product_types` VALUES ('261', '1', '261', 'Orange peel');
INSERT INTO `a_languages_a_product_types` VALUES ('262', '1', '262', 'Orange-grapefruit juice');
INSERT INTO `a_languages_a_product_types` VALUES ('263', '1', '263', 'Tangerines');
INSERT INTO `a_languages_a_product_types` VALUES ('264', '1', '264', 'Tangerine juice');
INSERT INTO `a_languages_a_product_types` VALUES ('265', '1', '265', 'Papayas');
INSERT INTO `a_languages_a_product_types` VALUES ('266', '1', '266', 'Papaya');
INSERT INTO `a_languages_a_product_types` VALUES ('267', '1', '267', 'Papaya nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('268', '1', '268', 'Passion-fruit');
INSERT INTO `a_languages_a_product_types` VALUES ('269', '1', '269', 'Passion-fruit juice');
INSERT INTO `a_languages_a_product_types` VALUES ('270', '1', '270', 'Peaches');
INSERT INTO `a_languages_a_product_types` VALUES ('271', '1', '271', 'Peach nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('272', '1', '272', 'Pears');
INSERT INTO `a_languages_a_product_types` VALUES ('273', '1', '273', 'Pear nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('274', '1', '274', 'Persimmons');
INSERT INTO `a_languages_a_product_types` VALUES ('275', '1', '275', 'Pineapple');
INSERT INTO `a_languages_a_product_types` VALUES ('276', '1', '276', 'Pineapple juice');
INSERT INTO `a_languages_a_product_types` VALUES ('277', '1', '277', 'Pitanga');
INSERT INTO `a_languages_a_product_types` VALUES ('278', '1', '278', 'Plantains');
INSERT INTO `a_languages_a_product_types` VALUES ('279', '1', '279', 'Plums');
INSERT INTO `a_languages_a_product_types` VALUES ('280', '1', '280', 'Pomegranates');
INSERT INTO `a_languages_a_product_types` VALUES ('281', '1', '281', 'Prickly pears');
INSERT INTO `a_languages_a_product_types` VALUES ('282', '1', '282', 'Prunes');
INSERT INTO `a_languages_a_product_types` VALUES ('283', '1', '283', 'Prune juice');
INSERT INTO `a_languages_a_product_types` VALUES ('284', '1', '284', 'Pummelo');
INSERT INTO `a_languages_a_product_types` VALUES ('285', '1', '285', 'Quinces');
INSERT INTO `a_languages_a_product_types` VALUES ('286', '1', '286', 'Raisins');
INSERT INTO `a_languages_a_product_types` VALUES ('287', '1', '287', 'Rambutan');
INSERT INTO `a_languages_a_product_types` VALUES ('288', '1', '288', 'Raspberries');
INSERT INTO `a_languages_a_product_types` VALUES ('289', '1', '289', 'Rhubarb');
INSERT INTO `a_languages_a_product_types` VALUES ('290', '1', '290', 'Roselle');
INSERT INTO `a_languages_a_product_types` VALUES ('291', '1', '291', 'Rose-apples');
INSERT INTO `a_languages_a_product_types` VALUES ('292', '1', '292', 'Sapodilla');
INSERT INTO `a_languages_a_product_types` VALUES ('293', '1', '293', 'Sapote');
INSERT INTO `a_languages_a_product_types` VALUES ('294', '1', '294', 'Soursop');
INSERT INTO `a_languages_a_product_types` VALUES ('295', '1', '295', 'Strawberries');
INSERT INTO `a_languages_a_product_types` VALUES ('296', '1', '296', 'Sugar-apples');
INSERT INTO `a_languages_a_product_types` VALUES ('297', '1', '297', 'Tamarinds');
INSERT INTO `a_languages_a_product_types` VALUES ('298', '1', '298', 'Watermelon');
INSERT INTO `a_languages_a_product_types` VALUES ('299', '1', '299', 'Maraschino cherries');
INSERT INTO `a_languages_a_product_types` VALUES ('300', '1', '300', 'Feijoa');
INSERT INTO `a_languages_a_product_types` VALUES ('301', '1', '301', 'Durian');
INSERT INTO `a_languages_a_product_types` VALUES ('302', '1', '302', 'Prune puree');
INSERT INTO `a_languages_a_product_types` VALUES ('303', '1', '303', 'Candied fruit');
INSERT INTO `a_languages_a_product_types` VALUES ('304', '1', '304', 'Abiyuch');
INSERT INTO `a_languages_a_product_types` VALUES ('305', '1', '305', 'Rowal');
INSERT INTO `a_languages_a_product_types` VALUES ('306', '1', '306', 'Clementines');
INSERT INTO `a_languages_a_product_types` VALUES ('307', '1', '307', 'Guanabana nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('308', '1', '308', 'Guava nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('309', '1', '309', 'Mango nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('310', '1', '310', 'Tamarind nectar');
INSERT INTO `a_languages_a_product_types` VALUES ('311', '1', '311', 'USDA Commodity peaches');
INSERT INTO `a_languages_a_product_types` VALUES ('312', '1', '312', 'USDA Commodity pears');
INSERT INTO `a_languages_a_product_types` VALUES ('313', '1', '313', 'Pomegranate juice');
INSERT INTO `a_languages_a_product_types` VALUES ('314', '1', '314', 'Juice');
INSERT INTO `a_languages_a_product_types` VALUES ('315', '1', '315', 'Nance');
INSERT INTO `a_languages_a_product_types` VALUES ('316', '1', '316', 'Naranjilla (lulo) pulp');
INSERT INTO `a_languages_a_product_types` VALUES ('317', '1', '317', 'Horned melon (Kiwano)');
INSERT INTO `a_languages_a_product_types` VALUES ('318', '1', '318', 'Pork');
INSERT INTO `a_languages_a_product_types` VALUES ('319', '1', '319', 'HORMEL');
INSERT INTO `a_languages_a_product_types` VALUES ('320', '1', '320', 'HORMEL ALWAYS TENDER');
INSERT INTO `a_languages_a_product_types` VALUES ('321', '1', '321', 'HORMEL Canadian Style Bacon');
INSERT INTO `a_languages_a_product_types` VALUES ('322', '1', '322', 'Alfalfa seeds');
INSERT INTO `a_languages_a_product_types` VALUES ('323', '1', '323', 'Amaranth leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('324', '1', '324', 'Arrowhead');
INSERT INTO `a_languages_a_product_types` VALUES ('325', '1', '325', 'Artichokes');
INSERT INTO `a_languages_a_product_types` VALUES ('326', '1', '326', 'Asparagus');
INSERT INTO `a_languages_a_product_types` VALUES ('327', '1', '327', 'Balsam-pear (bitter gourd)');
INSERT INTO `a_languages_a_product_types` VALUES ('328', '1', '328', 'Bamboo shoots');
INSERT INTO `a_languages_a_product_types` VALUES ('329', '1', '329', 'Beans');
INSERT INTO `a_languages_a_product_types` VALUES ('330', '1', '330', 'Lima beans');
INSERT INTO `a_languages_a_product_types` VALUES ('331', '1', '331', 'Mung beans');
INSERT INTO `a_languages_a_product_types` VALUES ('332', '1', '332', 'Beets');
INSERT INTO `a_languages_a_product_types` VALUES ('333', '1', '333', 'Beet greens');
INSERT INTO `a_languages_a_product_types` VALUES ('334', '1', '334', 'Broadbeans');
INSERT INTO `a_languages_a_product_types` VALUES ('335', '1', '335', 'Broccoli');
INSERT INTO `a_languages_a_product_types` VALUES ('336', '1', '336', 'Broccoli raab');
INSERT INTO `a_languages_a_product_types` VALUES ('337', '1', '337', 'Brussels sprouts');
INSERT INTO `a_languages_a_product_types` VALUES ('338', '1', '338', 'Burdock root');
INSERT INTO `a_languages_a_product_types` VALUES ('339', '1', '339', 'Butterbur');
INSERT INTO `a_languages_a_product_types` VALUES ('340', '1', '340', 'Cabbage');
INSERT INTO `a_languages_a_product_types` VALUES ('341', '1', '341', 'Cardoon');
INSERT INTO `a_languages_a_product_types` VALUES ('342', '1', '342', 'Carrots');
INSERT INTO `a_languages_a_product_types` VALUES ('343', '1', '343', 'Cassava');
INSERT INTO `a_languages_a_product_types` VALUES ('344', '1', '344', 'Cauliflower');
INSERT INTO `a_languages_a_product_types` VALUES ('345', '1', '345', 'Celeriac');
INSERT INTO `a_languages_a_product_types` VALUES ('346', '1', '346', 'Celery');
INSERT INTO `a_languages_a_product_types` VALUES ('347', '1', '347', 'Celtuce');
INSERT INTO `a_languages_a_product_types` VALUES ('348', '1', '348', 'Chard');
INSERT INTO `a_languages_a_product_types` VALUES ('349', '1', '349', 'Chayote');
INSERT INTO `a_languages_a_product_types` VALUES ('350', '1', '350', 'Chicory');
INSERT INTO `a_languages_a_product_types` VALUES ('351', '1', '351', 'Chicory greens');
INSERT INTO `a_languages_a_product_types` VALUES ('352', '1', '352', 'Chicory roots');
INSERT INTO `a_languages_a_product_types` VALUES ('353', '1', '353', 'Chives');
INSERT INTO `a_languages_a_product_types` VALUES ('354', '1', '354', 'Chrysanthemum');
INSERT INTO `a_languages_a_product_types` VALUES ('355', '1', '355', 'Coleslaw');
INSERT INTO `a_languages_a_product_types` VALUES ('356', '1', '356', 'Collards');
INSERT INTO `a_languages_a_product_types` VALUES ('357', '1', '357', 'Coriander (cilantro) leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('358', '1', '358', 'Corn');
INSERT INTO `a_languages_a_product_types` VALUES ('359', '1', '359', 'Corn with red and green pepper');
INSERT INTO `a_languages_a_product_types` VALUES ('360', '1', '360', 'Cornsalad');
INSERT INTO `a_languages_a_product_types` VALUES ('361', '1', '361', 'Cowpeas (blackeyes)');
INSERT INTO `a_languages_a_product_types` VALUES ('362', '1', '362', 'Cowpeas');
INSERT INTO `a_languages_a_product_types` VALUES ('363', '1', '363', 'Yardlong bean');
INSERT INTO `a_languages_a_product_types` VALUES ('364', '1', '364', 'Cress');
INSERT INTO `a_languages_a_product_types` VALUES ('365', '1', '365', 'Cucumber');
INSERT INTO `a_languages_a_product_types` VALUES ('366', '1', '366', 'Dandelion greens');
INSERT INTO `a_languages_a_product_types` VALUES ('367', '1', '367', 'Eggplant');
INSERT INTO `a_languages_a_product_types` VALUES ('368', '1', '368', 'Edamame');
INSERT INTO `a_languages_a_product_types` VALUES ('369', '1', '369', 'Endive');
INSERT INTO `a_languages_a_product_types` VALUES ('370', '1', '370', 'Garlic');
INSERT INTO `a_languages_a_product_types` VALUES ('371', '1', '371', 'Ginger root');
INSERT INTO `a_languages_a_product_types` VALUES ('372', '1', '372', 'Gourd');
INSERT INTO `a_languages_a_product_types` VALUES ('373', '1', '373', 'Horseradish-tree leafy tips');
INSERT INTO `a_languages_a_product_types` VALUES ('374', '1', '374', 'Horseradish-tree');
INSERT INTO `a_languages_a_product_types` VALUES ('375', '1', '375', 'Hyacinth-beans');
INSERT INTO `a_languages_a_product_types` VALUES ('376', '1', '376', 'Jerusalem-artichokes');
INSERT INTO `a_languages_a_product_types` VALUES ('377', '1', '377', 'Jew\'s ear');
INSERT INTO `a_languages_a_product_types` VALUES ('378', '1', '378', 'Pepeao');
INSERT INTO `a_languages_a_product_types` VALUES ('379', '1', '379', 'Jute');
INSERT INTO `a_languages_a_product_types` VALUES ('380', '1', '380', 'Kale');
INSERT INTO `a_languages_a_product_types` VALUES ('381', '1', '381', 'Kanpyo');
INSERT INTO `a_languages_a_product_types` VALUES ('382', '1', '382', 'Mushrooms');
INSERT INTO `a_languages_a_product_types` VALUES ('383', '1', '383', 'Kohlrabi');
INSERT INTO `a_languages_a_product_types` VALUES ('384', '1', '384', 'Lambsquarters');
INSERT INTO `a_languages_a_product_types` VALUES ('385', '1', '385', 'Leeks');
INSERT INTO `a_languages_a_product_types` VALUES ('386', '1', '386', 'Lentils');
INSERT INTO `a_languages_a_product_types` VALUES ('387', '1', '387', 'Lettuce');
INSERT INTO `a_languages_a_product_types` VALUES ('388', '1', '388', 'Lotus root');
INSERT INTO `a_languages_a_product_types` VALUES ('389', '1', '389', 'Mountain yam');
INSERT INTO `a_languages_a_product_types` VALUES ('390', '1', '390', 'Mustard greens');
INSERT INTO `a_languages_a_product_types` VALUES ('391', '1', '391', 'Mustard spinach');
INSERT INTO `a_languages_a_product_types` VALUES ('392', '1', '392', 'New Zealand spinach');
INSERT INTO `a_languages_a_product_types` VALUES ('393', '1', '393', 'Okra');
INSERT INTO `a_languages_a_product_types` VALUES ('394', '1', '394', 'Onions');
INSERT INTO `a_languages_a_product_types` VALUES ('395', '1', '395', 'Onion rings');
INSERT INTO `a_languages_a_product_types` VALUES ('396', '1', '396', 'Parsley');
INSERT INTO `a_languages_a_product_types` VALUES ('397', '1', '397', 'Parsnips');
INSERT INTO `a_languages_a_product_types` VALUES ('398', '1', '398', 'Peas');
INSERT INTO `a_languages_a_product_types` VALUES ('399', '1', '399', 'Peas and carrots');
INSERT INTO `a_languages_a_product_types` VALUES ('400', '1', '400', 'Peas and onions');
INSERT INTO `a_languages_a_product_types` VALUES ('401', '1', '401', 'Peppers');
INSERT INTO `a_languages_a_product_types` VALUES ('402', '1', '402', 'Pigeonpeas');
INSERT INTO `a_languages_a_product_types` VALUES ('403', '1', '403', 'Poi');
INSERT INTO `a_languages_a_product_types` VALUES ('404', '1', '404', 'Pokeberry shoots');
INSERT INTO `a_languages_a_product_types` VALUES ('405', '1', '405', 'Potato');
INSERT INTO `a_languages_a_product_types` VALUES ('406', '1', '406', 'Potatoes');
INSERT INTO `a_languages_a_product_types` VALUES ('407', '1', '407', 'Potato puffs');
INSERT INTO `a_languages_a_product_types` VALUES ('408', '1', '408', 'Potato flour');
INSERT INTO `a_languages_a_product_types` VALUES ('409', '1', '409', 'Potato salad');
INSERT INTO `a_languages_a_product_types` VALUES ('410', '1', '410', 'Pumpkin flowers');
INSERT INTO `a_languages_a_product_types` VALUES ('411', '1', '411', 'Pumpkin leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('412', '1', '412', 'Pumpkin');
INSERT INTO `a_languages_a_product_types` VALUES ('413', '1', '413', 'Pumpkin pie mix');
INSERT INTO `a_languages_a_product_types` VALUES ('414', '1', '414', 'Purslane');
INSERT INTO `a_languages_a_product_types` VALUES ('415', '1', '415', 'Radishes');
INSERT INTO `a_languages_a_product_types` VALUES ('416', '1', '416', 'Rutabagas');
INSERT INTO `a_languages_a_product_types` VALUES ('417', '1', '417', 'Salsify');
INSERT INTO `a_languages_a_product_types` VALUES ('418', '1', '418', 'Sauerkraut');
INSERT INTO `a_languages_a_product_types` VALUES ('419', '1', '419', 'Seaweed');
INSERT INTO `a_languages_a_product_types` VALUES ('420', '1', '420', 'Sesbania flower');
INSERT INTO `a_languages_a_product_types` VALUES ('421', '1', '421', 'Soybeans');
INSERT INTO `a_languages_a_product_types` VALUES ('422', '1', '422', 'Spinach');
INSERT INTO `a_languages_a_product_types` VALUES ('423', '1', '423', 'Squash');
INSERT INTO `a_languages_a_product_types` VALUES ('424', '1', '424', 'Succotash');
INSERT INTO `a_languages_a_product_types` VALUES ('425', '1', '425', 'Swamp cabbage');
INSERT INTO `a_languages_a_product_types` VALUES ('426', '1', '426', 'Sweet potato leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('427', '1', '427', 'Sweet potato');
INSERT INTO `a_languages_a_product_types` VALUES ('428', '1', '428', 'Taro');
INSERT INTO `a_languages_a_product_types` VALUES ('429', '1', '429', 'Taro leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('430', '1', '430', 'Taro shoots');
INSERT INTO `a_languages_a_product_types` VALUES ('431', '1', '431', 'Tomatoes');
INSERT INTO `a_languages_a_product_types` VALUES ('432', '1', '432', 'Tomato juice');
INSERT INTO `a_languages_a_product_types` VALUES ('433', '1', '433', 'Tomato products');
INSERT INTO `a_languages_a_product_types` VALUES ('434', '1', '434', 'Tomato powder');
INSERT INTO `a_languages_a_product_types` VALUES ('435', '1', '435', 'Tree fern');
INSERT INTO `a_languages_a_product_types` VALUES ('436', '1', '436', 'Turnips');
INSERT INTO `a_languages_a_product_types` VALUES ('437', '1', '437', 'Turnip greens');
INSERT INTO `a_languages_a_product_types` VALUES ('438', '1', '438', 'Turnip greens and turnips');
INSERT INTO `a_languages_a_product_types` VALUES ('439', '1', '439', 'Vegetable juice cocktail');
INSERT INTO `a_languages_a_product_types` VALUES ('440', '1', '440', 'Vegetables');
INSERT INTO `a_languages_a_product_types` VALUES ('441', '1', '441', 'Vinespinach');
INSERT INTO `a_languages_a_product_types` VALUES ('442', '1', '442', 'Waterchestnuts');
INSERT INTO `a_languages_a_product_types` VALUES ('443', '1', '443', 'Watercress');
INSERT INTO `a_languages_a_product_types` VALUES ('444', '1', '444', 'Waxgourd');
INSERT INTO `a_languages_a_product_types` VALUES ('445', '1', '445', 'Winged beans');
INSERT INTO `a_languages_a_product_types` VALUES ('446', '1', '446', 'Winged bean leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('447', '1', '447', 'Winged bean tuber');
INSERT INTO `a_languages_a_product_types` VALUES ('448', '1', '448', 'Yam');
INSERT INTO `a_languages_a_product_types` VALUES ('449', '1', '449', 'Yambean (jicama)');
INSERT INTO `a_languages_a_product_types` VALUES ('450', '1', '450', 'Borage');
INSERT INTO `a_languages_a_product_types` VALUES ('451', '1', '451', 'Dock');
INSERT INTO `a_languages_a_product_types` VALUES ('452', '1', '452', 'Eppaw');
INSERT INTO `a_languages_a_product_types` VALUES ('453', '1', '453', 'Shallots');
INSERT INTO `a_languages_a_product_types` VALUES ('454', '1', '454', 'Carrot juice');
INSERT INTO `a_languages_a_product_types` VALUES ('455', '1', '455', 'Corn pudding');
INSERT INTO `a_languages_a_product_types` VALUES ('456', '1', '456', 'Spinach souffle');
INSERT INTO `a_languages_a_product_types` VALUES ('457', '1', '457', 'Potato pancakes');
INSERT INTO `a_languages_a_product_types` VALUES ('458', '1', '458', 'Radish seeds');
INSERT INTO `a_languages_a_product_types` VALUES ('459', '1', '459', 'Carrot');
INSERT INTO `a_languages_a_product_types` VALUES ('460', '1', '460', 'Arrowroot');
INSERT INTO `a_languages_a_product_types` VALUES ('461', '1', '461', 'Chrysanthemum leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('462', '1', '462', 'Lambs quarters');
INSERT INTO `a_languages_a_product_types` VALUES ('463', '1', '463', 'Winged bean');
INSERT INTO `a_languages_a_product_types` VALUES ('464', '1', '464', 'Catsup');
INSERT INTO `a_languages_a_product_types` VALUES ('465', '1', '465', 'Pickles');
INSERT INTO `a_languages_a_product_types` VALUES ('466', '1', '466', 'Pimento');
INSERT INTO `a_languages_a_product_types` VALUES ('467', '1', '467', 'Pickle relish');
INSERT INTO `a_languages_a_product_types` VALUES ('468', '1', '468', 'Radicchio');
INSERT INTO `a_languages_a_product_types` VALUES ('469', '1', '469', 'Tomatillos');
INSERT INTO `a_languages_a_product_types` VALUES ('470', '1', '470', 'Fennel');
INSERT INTO `a_languages_a_product_types` VALUES ('471', '1', '471', 'Arugula');
INSERT INTO `a_languages_a_product_types` VALUES ('472', '1', '472', 'Hearts of palm');
INSERT INTO `a_languages_a_product_types` VALUES ('473', '1', '473', 'Nopales');
INSERT INTO `a_languages_a_product_types` VALUES ('474', '1', '474', 'Lemon grass (citronella)');
INSERT INTO `a_languages_a_product_types` VALUES ('475', '1', '475', 'Grape leaves');
INSERT INTO `a_languages_a_product_types` VALUES ('476', '1', '476', 'Pepper');
INSERT INTO `a_languages_a_product_types` VALUES ('477', '1', '477', 'Epazote');
INSERT INTO `a_languages_a_product_types` VALUES ('478', '1', '478', 'Fireweed');
INSERT INTO `a_languages_a_product_types` VALUES ('479', '1', '479', 'Malabar spinach');
INSERT INTO `a_languages_a_product_types` VALUES ('480', '1', '480', 'Fungi');
INSERT INTO `a_languages_a_product_types` VALUES ('481', '1', '481', 'Wasabi');
INSERT INTO `a_languages_a_product_types` VALUES ('482', '1', '482', 'Yautia (tannier)');
INSERT INTO `a_languages_a_product_types` VALUES ('483', '1', '483', 'Fiddlehead ferns');
INSERT INTO `a_languages_a_product_types` VALUES ('484', '1', '484', 'Seeds');
INSERT INTO `a_languages_a_product_types` VALUES ('485', '1', '485', 'Nuts');
INSERT INTO `a_languages_a_product_types` VALUES ('486', '1', '486', 'Beef');
INSERT INTO `a_languages_a_product_types` VALUES ('487', '1', '487', 'Alcoholic beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('488', '1', '488', 'Whiskey sour mix');
INSERT INTO `a_languages_a_product_types` VALUES ('489', '1', '489', 'Beef broth and tomato juice');
INSERT INTO `a_languages_a_product_types` VALUES ('490', '1', '490', 'Mixed vegetable and fruit juic');
INSERT INTO `a_languages_a_product_types` VALUES ('491', '1', '491', 'Carbonated beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('492', '1', '492', 'Tea');
INSERT INTO `a_languages_a_product_types` VALUES ('493', '1', '493', 'Energy drink');
INSERT INTO `a_languages_a_product_types` VALUES ('494', '1', '494', 'Carob-flavor beverage mix');
INSERT INTO `a_languages_a_product_types` VALUES ('495', '1', '495', 'Chocolate-flavor beverage mix ');
INSERT INTO `a_languages_a_product_types` VALUES ('496', '1', '496', 'Chocolate syrup');
INSERT INTO `a_languages_a_product_types` VALUES ('497', '1', '497', 'Clam and tomato juice');
INSERT INTO `a_languages_a_product_types` VALUES ('498', '1', '498', 'Cocoa mix');
INSERT INTO `a_languages_a_product_types` VALUES ('499', '1', '499', 'Coffee');
INSERT INTO `a_languages_a_product_types` VALUES ('500', '1', '500', 'Coffee and cocoa (mocha) powde');
INSERT INTO `a_languages_a_product_types` VALUES ('501', '1', '501', 'Coffee substitute');
INSERT INTO `a_languages_a_product_types` VALUES ('502', '1', '502', 'Cranberry-apple juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('503', '1', '503', 'Cranberry-apricot juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('504', '1', '504', 'Cranberry-grape juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('505', '1', '505', 'Cranberry juice cocktail');
INSERT INTO `a_languages_a_product_types` VALUES ('506', '1', '506', 'Eggnog-flavor mix');
INSERT INTO `a_languages_a_product_types` VALUES ('507', '1', '507', 'Citrus fruit juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('508', '1', '508', 'Fruit punch drink');
INSERT INTO `a_languages_a_product_types` VALUES ('509', '1', '509', 'Grape drink');
INSERT INTO `a_languages_a_product_types` VALUES ('510', '1', '510', 'Grape juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('511', '1', '511', 'Lemonade');
INSERT INTO `a_languages_a_product_types` VALUES ('512', '1', '512', 'Lemonade-flavor drink');
INSERT INTO `a_languages_a_product_types` VALUES ('513', '1', '513', 'Limeade');
INSERT INTO `a_languages_a_product_types` VALUES ('514', '1', '514', 'Malt beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('515', '1', '515', 'Malted drink mix');
INSERT INTO `a_languages_a_product_types` VALUES ('516', '1', '516', 'Orange drink');
INSERT INTO `a_languages_a_product_types` VALUES ('517', '1', '517', 'Orange and apricot juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('518', '1', '518', 'Pineapple and grapefruit juice');
INSERT INTO `a_languages_a_product_types` VALUES ('519', '1', '519', 'Pineapple and orange juice dri');
INSERT INTO `a_languages_a_product_types` VALUES ('520', '1', '520', 'Shake');
INSERT INTO `a_languages_a_product_types` VALUES ('521', '1', '521', 'Strawberry-flavor beverage mix');
INSERT INTO `a_languages_a_product_types` VALUES ('522', '1', '522', 'Sports drink');
INSERT INTO `a_languages_a_product_types` VALUES ('523', '1', '523', 'Water');
INSERT INTO `a_languages_a_product_types` VALUES ('524', '1', '524', 'Fruit punch juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('525', '1', '525', 'Orange-flavor drink');
INSERT INTO `a_languages_a_product_types` VALUES ('526', '1', '526', 'Dairy drink mix');
INSERT INTO `a_languages_a_product_types` VALUES ('527', '1', '527', 'Orange breakfast drink');
INSERT INTO `a_languages_a_product_types` VALUES ('528', '1', '528', 'Drink mix');
INSERT INTO `a_languages_a_product_types` VALUES ('529', '1', '529', 'QUAKER OATS');
INSERT INTO `a_languages_a_product_types` VALUES ('530', '1', '530', 'Fruit punch-flavor drink');
INSERT INTO `a_languages_a_product_types` VALUES ('531', '1', '531', 'Wine');
INSERT INTO `a_languages_a_product_types` VALUES ('532', '1', '532', 'Chocolate-flavor beverage mix ');
INSERT INTO `a_languages_a_product_types` VALUES ('533', '1', '533', 'Chocolate-flavor beverage mix ');
INSERT INTO `a_languages_a_product_types` VALUES ('534', '1', '534', 'Water with added vitamins and ');
INSERT INTO `a_languages_a_product_types` VALUES ('535', '1', '535', 'Breakfast type drink');
INSERT INTO `a_languages_a_product_types` VALUES ('536', '1', '536', 'Beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('537', '1', '537', 'Meal supplement drink');
INSERT INTO `a_languages_a_product_types` VALUES ('538', '1', '538', 'Vegetable and fruit juice drin');
INSERT INTO `a_languages_a_product_types` VALUES ('539', '1', '539', 'Ready-to-drink reduced fat mil');
INSERT INTO `a_languages_a_product_types` VALUES ('540', '1', '540', 'Beverages');
INSERT INTO `a_languages_a_product_types` VALUES ('541', '1', '541', 'Rice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('542', '1', '542', 'Fish');
INSERT INTO `a_languages_a_product_types` VALUES ('543', '1', '543', 'Crustaceans');
INSERT INTO `a_languages_a_product_types` VALUES ('544', '1', '544', 'Mollusks');
INSERT INTO `a_languages_a_product_types` VALUES ('545', '1', '545', 'Broadbeans (fava beans)');
INSERT INTO `a_languages_a_product_types` VALUES ('546', '1', '546', 'Carob flour');
INSERT INTO `a_languages_a_product_types` VALUES ('547', '1', '547', 'Chickpeas (garbanzo beans');
INSERT INTO `a_languages_a_product_types` VALUES ('548', '1', '548', 'Chili with beans');
INSERT INTO `a_languages_a_product_types` VALUES ('549', '1', '549', 'Hyacinth beans');
INSERT INTO `a_languages_a_product_types` VALUES ('550', '1', '550', 'Lupins');
INSERT INTO `a_languages_a_product_types` VALUES ('551', '1', '551', 'Mothbeans');
INSERT INTO `a_languages_a_product_types` VALUES ('552', '1', '552', 'Noodles');
INSERT INTO `a_languages_a_product_types` VALUES ('553', '1', '553', 'Mungo beans');
INSERT INTO `a_languages_a_product_types` VALUES ('554', '1', '554', 'Peanuts');
INSERT INTO `a_languages_a_product_types` VALUES ('555', '1', '555', 'Peanut butter');
INSERT INTO `a_languages_a_product_types` VALUES ('556', '1', '556', 'Peanut flour');
INSERT INTO `a_languages_a_product_types` VALUES ('557', '1', '557', 'Pigeon peas (red gram)');
INSERT INTO `a_languages_a_product_types` VALUES ('558', '1', '558', 'Refried beans');
INSERT INTO `a_languages_a_product_types` VALUES ('559', '1', '559', 'Bacon');
INSERT INTO `a_languages_a_product_types` VALUES ('560', '1', '560', 'Meat extender');
INSERT INTO `a_languages_a_product_types` VALUES ('561', '1', '561', 'Miso');
INSERT INTO `a_languages_a_product_types` VALUES ('562', '1', '562', 'Natto');
INSERT INTO `a_languages_a_product_types` VALUES ('563', '1', '563', 'Tempeh');
INSERT INTO `a_languages_a_product_types` VALUES ('564', '1', '564', 'Soy flour');
INSERT INTO `a_languages_a_product_types` VALUES ('565', '1', '565', 'Soy meal');
INSERT INTO `a_languages_a_product_types` VALUES ('566', '1', '566', 'Soymilk');
INSERT INTO `a_languages_a_product_types` VALUES ('567', '1', '567', 'Soy protein concentrate');
INSERT INTO `a_languages_a_product_types` VALUES ('568', '1', '568', 'Soy protein isolate');
INSERT INTO `a_languages_a_product_types` VALUES ('569', '1', '569', 'Soy sauce made from soy and wh');
INSERT INTO `a_languages_a_product_types` VALUES ('570', '1', '570', 'Soy sauce made from soy (tamar');
INSERT INTO `a_languages_a_product_types` VALUES ('571', '1', '571', 'Soy sauce made from hydrolyzed');
INSERT INTO `a_languages_a_product_types` VALUES ('572', '1', '572', 'Tofu');
INSERT INTO `a_languages_a_product_types` VALUES ('573', '1', '573', 'Yardlong beans');
INSERT INTO `a_languages_a_product_types` VALUES ('574', '1', '574', 'Hummus');
INSERT INTO `a_languages_a_product_types` VALUES ('575', '1', '575', 'Falafel');
INSERT INTO `a_languages_a_product_types` VALUES ('576', '1', '576', 'Veggie burgers or soyburgers');
INSERT INTO `a_languages_a_product_types` VALUES ('577', '1', '577', 'Peanut spread');
INSERT INTO `a_languages_a_product_types` VALUES ('578', '1', '578', 'ENSURE FIBER WITH FOS');
INSERT INTO `a_languages_a_product_types` VALUES ('579', '1', '579', 'Chickpea flour (besan)');
INSERT INTO `a_languages_a_product_types` VALUES ('580', '1', '580', 'MORI-NU');
INSERT INTO `a_languages_a_product_types` VALUES ('581', '1', '581', 'Frijoles rojos volteados (Refr');
INSERT INTO `a_languages_a_product_types` VALUES ('582', '1', '582', 'Vitasoy USA');
INSERT INTO `a_languages_a_product_types` VALUES ('583', '1', '583', 'Soymilk (all flavors)');
INSERT INTO `a_languages_a_product_types` VALUES ('584', '1', '584', 'SILK Plain');
INSERT INTO `a_languages_a_product_types` VALUES ('585', '1', '585', 'SILK Vanilla');
INSERT INTO `a_languages_a_product_types` VALUES ('586', '1', '586', 'SILK Chocolate');
INSERT INTO `a_languages_a_product_types` VALUES ('587', '1', '587', 'SILK Light Plain');
INSERT INTO `a_languages_a_product_types` VALUES ('588', '1', '588', 'SILK Light Vanilla');
INSERT INTO `a_languages_a_product_types` VALUES ('589', '1', '589', 'SILK Light Chocolate');
INSERT INTO `a_languages_a_product_types` VALUES ('590', '1', '590', 'SILK Plus Omega-3 DHA');
INSERT INTO `a_languages_a_product_types` VALUES ('591', '1', '591', 'SILK Plus for Bone Health');
INSERT INTO `a_languages_a_product_types` VALUES ('592', '1', '592', 'SILK Plus Fiber');
INSERT INTO `a_languages_a_product_types` VALUES ('593', '1', '593', 'SILK Unsweetened');
INSERT INTO `a_languages_a_product_types` VALUES ('594', '1', '594', 'SILK Very Vanilla');
INSERT INTO `a_languages_a_product_types` VALUES ('595', '1', '595', 'SILK Nog');
INSERT INTO `a_languages_a_product_types` VALUES ('596', '1', '596', 'SILK Chai');
INSERT INTO `a_languages_a_product_types` VALUES ('597', '1', '597', 'SILK Mocha');
INSERT INTO `a_languages_a_product_types` VALUES ('598', '1', '598', 'SILK Coffee');
INSERT INTO `a_languages_a_product_types` VALUES ('599', '1', '599', 'SILK Vanilla soy Yogurt (Famil');
INSERT INTO `a_languages_a_product_types` VALUES ('600', '1', '600', 'SILK Vanilla soy yogurt (singl');
INSERT INTO `a_languages_a_product_types` VALUES ('601', '1', '601', 'SILK Plain soy yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('602', '1', '602', 'SILK Strawberry soy yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('603', '1', '603', 'SILK Raspberry soy yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('604', '1', '604', 'SILK Peach soy Yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('605', '1', '605', 'SILK Black Cherry soy Yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('606', '1', '606', 'SILK Blueberry soy Yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('607', '1', '607', 'SILK Key Lime soy Yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('608', '1', '608', 'SILK Banana-Strawberry soy Yog');
INSERT INTO `a_languages_a_product_types` VALUES ('609', '1', '609', 'SILK Original Creamer');
INSERT INTO `a_languages_a_product_types` VALUES ('610', '1', '610', 'SILK French Vanilla Creamer');
INSERT INTO `a_languages_a_product_types` VALUES ('611', '1', '611', 'SILK Hazelnut Creamer');
INSERT INTO `a_languages_a_product_types` VALUES ('612', '1', '612', 'Peanut butter with omega-3');
INSERT INTO `a_languages_a_product_types` VALUES ('613', '1', '613', 'Soy sauce made from soy and wh');
INSERT INTO `a_languages_a_product_types` VALUES ('614', '1', '614', 'LOMA LINDA Little Links');
INSERT INTO `a_languages_a_product_types` VALUES ('615', '1', '615', 'LOMA LINDA Low Fat Big Franks');
INSERT INTO `a_languages_a_product_types` VALUES ('616', '1', '616', 'LOMA LINDA Tender Rounds with ');
INSERT INTO `a_languages_a_product_types` VALUES ('617', '1', '617', 'LOMA LINDA Swiss Stake with Gr');
INSERT INTO `a_languages_a_product_types` VALUES ('618', '1', '618', 'LOMA LINDA Vege-Burger');
INSERT INTO `a_languages_a_product_types` VALUES ('619', '1', '619', 'LOMA LINDA Redi-Burger');
INSERT INTO `a_languages_a_product_types` VALUES ('620', '1', '620', 'LOMA LINDA Tender Bits');
INSERT INTO `a_languages_a_product_types` VALUES ('621', '1', '621', 'LOMA LINDA Linketts');
INSERT INTO `a_languages_a_product_types` VALUES ('622', '1', '622', 'WORTHINGTON Chili');
INSERT INTO `a_languages_a_product_types` VALUES ('623', '1', '623', 'WORTHINGTON Choplets');
INSERT INTO `a_languages_a_product_types` VALUES ('624', '1', '624', 'WORTHINGTON Diced Chik');
INSERT INTO `a_languages_a_product_types` VALUES ('625', '1', '625', 'WORTHINGTON FriChik Original');
INSERT INTO `a_languages_a_product_types` VALUES ('626', '1', '626', 'WORTHINGTON Low Fat Fri Chik');
INSERT INTO `a_languages_a_product_types` VALUES ('627', '1', '627', 'WORTHINGTON Low Fat Veja-Links');
INSERT INTO `a_languages_a_product_types` VALUES ('628', '1', '628', 'WORTHINGTON Multigrain Cutlets');
INSERT INTO `a_languages_a_product_types` VALUES ('629', '1', '629', 'WORTHINGTON Prime Stakes');
INSERT INTO `a_languages_a_product_types` VALUES ('630', '1', '630', 'WORTHINGTON Saucettes');
INSERT INTO `a_languages_a_product_types` VALUES ('631', '1', '631', 'WORTHINGTON Super Links');
INSERT INTO `a_languages_a_product_types` VALUES ('632', '1', '632', 'WORTHINGTON Vegetable Skallops');
INSERT INTO `a_languages_a_product_types` VALUES ('633', '1', '633', 'WORTHINGTON Vegetable Steaks');
INSERT INTO `a_languages_a_product_types` VALUES ('634', '1', '634', 'WORTHINGTON Vegetarian Burger');
INSERT INTO `a_languages_a_product_types` VALUES ('635', '1', '635', 'WORTHINGTON Veja-Links');
INSERT INTO `a_languages_a_product_types` VALUES ('636', '1', '636', 'WORTHINGTON Chic-Ketts');
INSERT INTO `a_languages_a_product_types` VALUES ('637', '1', '637', 'WORTHINGTON Meatless Chicken R');
INSERT INTO `a_languages_a_product_types` VALUES ('638', '1', '638', 'WORTHINGTON Meatless Corned Be');
INSERT INTO `a_languages_a_product_types` VALUES ('639', '1', '639', 'WORTHINGTON Dinner Roast');
INSERT INTO `a_languages_a_product_types` VALUES ('640', '1', '640', 'WORTHINGTON FriPats');
INSERT INTO `a_languages_a_product_types` VALUES ('641', '1', '641', 'WORTHINGTON Prosage Links');
INSERT INTO `a_languages_a_product_types` VALUES ('642', '1', '642', 'WORTHINGTON Prosage Roll');
INSERT INTO `a_languages_a_product_types` VALUES ('643', '1', '643', 'WORTHINGTON Smoked Turkey Roll');
INSERT INTO `a_languages_a_product_types` VALUES ('644', '1', '644', 'WORTHINGTON Stakelets');
INSERT INTO `a_languages_a_product_types` VALUES ('645', '1', '645', 'WORTHINGTON Stripples');
INSERT INTO `a_languages_a_product_types` VALUES ('646', '1', '646', 'WORTHINGTON Wham (roll)');
INSERT INTO `a_languages_a_product_types` VALUES ('647', '1', '647', 'MORNINGSTAR FARMS Breakfast Pa');
INSERT INTO `a_languages_a_product_types` VALUES ('648', '1', '648', 'MORNINGSTAR FARMS Veggie Break');
INSERT INTO `a_languages_a_product_types` VALUES ('649', '1', '649', 'MORNINGSTAR FARMS Veggie Break');
INSERT INTO `a_languages_a_product_types` VALUES ('650', '1', '650', 'MORNINGSTAR FARMS Grillers Ori');
INSERT INTO `a_languages_a_product_types` VALUES ('651', '1', '651', 'MORNINGSTAR FARMS Grillers Pri');
INSERT INTO `a_languages_a_product_types` VALUES ('652', '1', '652', 'MORNINGSTAR FARMS Asian Veggie');
INSERT INTO `a_languages_a_product_types` VALUES ('653', '1', '653', 'MORNINGSTAR FARMS Mushroom Lov');
INSERT INTO `a_languages_a_product_types` VALUES ('654', '1', '654', 'MORNINGSTAR FARMS Tomato & Bas');
INSERT INTO `a_languages_a_product_types` VALUES ('655', '1', '655', 'MORNINGSTAR FARMS MeatFree Buf');
INSERT INTO `a_languages_a_product_types` VALUES ('656', '1', '656', 'MORNINGSTAR FARMS Chik\'n Nugge');
INSERT INTO `a_languages_a_product_types` VALUES ('657', '1', '657', 'MORNINGSTAR FARMS Chik Patties');
INSERT INTO `a_languages_a_product_types` VALUES ('658', '1', '658', 'MORNINGSTAR FARMS Italian Herb');
INSERT INTO `a_languages_a_product_types` VALUES ('659', '1', '659', 'MORNINGSTAR FARMS Original Chi');
INSERT INTO `a_languages_a_product_types` VALUES ('660', '1', '660', 'MORNINGSTAR FARMS Meal Starter');
INSERT INTO `a_languages_a_product_types` VALUES ('661', '1', '661', 'MORNINGSTAR FARMS Sausage Styl');
INSERT INTO `a_languages_a_product_types` VALUES ('662', '1', '662', 'GARDENBURGER');
INSERT INTO `a_languages_a_product_types` VALUES ('663', '1', '663', 'GARDENBURGER Breaded Chik\'n Ve');
INSERT INTO `a_languages_a_product_types` VALUES ('664', '1', '664', 'MORNINGSTAR FARMS Maple Flavor');
INSERT INTO `a_languages_a_product_types` VALUES ('665', '1', '665', 'MORNINGSTAR FARMS Chik\'n Grill');
INSERT INTO `a_languages_a_product_types` VALUES ('666', '1', '666', 'MORNINGSTAR FARMS Veggie Itali');
INSERT INTO `a_languages_a_product_types` VALUES ('667', '1', '667', 'MORNINGSTAR FARMS BBQ Riblets');
INSERT INTO `a_languages_a_product_types` VALUES ('668', '1', '668', 'WORTHINGTON Leanies');
INSERT INTO `a_languages_a_product_types` VALUES ('669', '1', '669', 'MORNINGSTAR FARMS California T');
INSERT INTO `a_languages_a_product_types` VALUES ('670', '1', '670', 'MORNINGSTAR FARMS Hot and Spic');
INSERT INTO `a_languages_a_product_types` VALUES ('671', '1', '671', 'MORNINGSTAR FARMS Lasagna with');
INSERT INTO `a_languages_a_product_types` VALUES ('672', '1', '672', 'MORNINGSTAR FARMS Veggie Sweet');
INSERT INTO `a_languages_a_product_types` VALUES ('673', '1', '673', 'MORNINGSTAR FARMS Grillers Qua');
INSERT INTO `a_languages_a_product_types` VALUES ('674', '1', '674', 'Lamb');
INSERT INTO `a_languages_a_product_types` VALUES ('675', '1', '675', 'Veal');
INSERT INTO `a_languages_a_product_types` VALUES ('676', '1', '676', 'Game meat');
INSERT INTO `a_languages_a_product_types` VALUES ('677', '1', '677', 'Bison');
INSERT INTO `a_languages_a_product_types` VALUES ('678', '1', '678', 'Goat');
INSERT INTO `a_languages_a_product_types` VALUES ('679', '1', '679', 'Bagels');
INSERT INTO `a_languages_a_product_types` VALUES ('680', '1', '680', 'Biscuits');
INSERT INTO `a_languages_a_product_types` VALUES ('681', '1', '681', 'Bread');
INSERT INTO `a_languages_a_product_types` VALUES ('682', '1', '682', 'Bread crumbs');
INSERT INTO `a_languages_a_product_types` VALUES ('683', '1', '683', 'Bread sticks');
INSERT INTO `a_languages_a_product_types` VALUES ('684', '1', '684', 'Bread stuffing');
INSERT INTO `a_languages_a_product_types` VALUES ('685', '1', '685', 'Cake');
INSERT INTO `a_languages_a_product_types` VALUES ('686', '1', '686', 'Coffeecake');
INSERT INTO `a_languages_a_product_types` VALUES ('687', '1', '687', 'Cheesecake commercially prepar');
INSERT INTO `a_languages_a_product_types` VALUES ('688', '1', '688', 'Cheesecake prepared from mix');
INSERT INTO `a_languages_a_product_types` VALUES ('689', '1', '689', 'Cookies');
INSERT INTO `a_languages_a_product_types` VALUES ('690', '1', '690', 'Puff pastry');
INSERT INTO `a_languages_a_product_types` VALUES ('691', '1', '691', 'Crackers');
INSERT INTO `a_languages_a_product_types` VALUES ('692', '1', '692', 'Cracker meal');
INSERT INTO `a_languages_a_product_types` VALUES ('693', '1', '693', 'Cream puffs');
INSERT INTO `a_languages_a_product_types` VALUES ('694', '1', '694', 'Croissants');
INSERT INTO `a_languages_a_product_types` VALUES ('695', '1', '695', 'Croutons');
INSERT INTO `a_languages_a_product_types` VALUES ('696', '1', '696', 'Danish pastry');
INSERT INTO `a_languages_a_product_types` VALUES ('697', '1', '697', 'Doughnuts');
INSERT INTO `a_languages_a_product_types` VALUES ('698', '1', '698', 'Eclairs');
INSERT INTO `a_languages_a_product_types` VALUES ('699', '1', '699', 'English muffins');
INSERT INTO `a_languages_a_product_types` VALUES ('700', '1', '700', 'French toast');
INSERT INTO `a_languages_a_product_types` VALUES ('701', '1', '701', 'Hush puppies');
INSERT INTO `a_languages_a_product_types` VALUES ('702', '1', '702', 'Ice cream cones');
INSERT INTO `a_languages_a_product_types` VALUES ('703', '1', '703', 'Muffins');
INSERT INTO `a_languages_a_product_types` VALUES ('704', '1', '704', 'Pancakes plain');
INSERT INTO `a_languages_a_product_types` VALUES ('705', '1', '705', 'Pancakes');
INSERT INTO `a_languages_a_product_types` VALUES ('706', '1', '706', 'Pie');
INSERT INTO `a_languages_a_product_types` VALUES ('707', '1', '707', 'Pie crust');
INSERT INTO `a_languages_a_product_types` VALUES ('708', '1', '708', 'Phyllo dough');
INSERT INTO `a_languages_a_product_types` VALUES ('709', '1', '709', 'Popovers');
INSERT INTO `a_languages_a_product_types` VALUES ('710', '1', '710', 'Rolls');
INSERT INTO `a_languages_a_product_types` VALUES ('711', '1', '711', 'Strudel');
INSERT INTO `a_languages_a_product_types` VALUES ('712', '1', '712', 'Sweet rolls');
INSERT INTO `a_languages_a_product_types` VALUES ('713', '1', '713', 'Taco shells');
INSERT INTO `a_languages_a_product_types` VALUES ('714', '1', '714', 'Toaster pastries');
INSERT INTO `a_languages_a_product_types` VALUES ('715', '1', '715', 'Tortillas');
INSERT INTO `a_languages_a_product_types` VALUES ('716', '1', '716', 'Waffles');
INSERT INTO `a_languages_a_product_types` VALUES ('717', '1', '717', 'Wonton wrappers (includes egg ');
INSERT INTO `a_languages_a_product_types` VALUES ('718', '1', '718', 'Leavening agents');
INSERT INTO `a_languages_a_product_types` VALUES ('719', '1', '719', 'Breakfast tart');
INSERT INTO `a_languages_a_product_types` VALUES ('720', '1', '720', 'KELLOGG');
INSERT INTO `a_languages_a_product_types` VALUES ('721', '1', '721', 'KELLOGG\'S Eggo Lowfat Homestyl');
INSERT INTO `a_languages_a_product_types` VALUES ('722', '1', '722', 'KELLOGG\'S Eggo Lowfat Nutri-Gr');
INSERT INTO `a_languages_a_product_types` VALUES ('723', '1', '723', 'KELLOGG\'S Eggo Lowfat Blueberr');
INSERT INTO `a_languages_a_product_types` VALUES ('724', '1', '724', 'KELLOGG\'S Pop-Tarts Pastry Swi');
INSERT INTO `a_languages_a_product_types` VALUES ('725', '1', '725', 'KELLOGG\'S Pop-Tarts Pastry Swi');
INSERT INTO `a_languages_a_product_types` VALUES ('726', '1', '726', 'KELLOGG\'S Pop-Tarts Pastry Swi');
INSERT INTO `a_languages_a_product_types` VALUES ('727', '1', '727', 'KELLOGG\'S Eggo Golden Oat Waff');
INSERT INTO `a_languages_a_product_types` VALUES ('728', '1', '728', 'ARCHWAY Home Style Cookies');
INSERT INTO `a_languages_a_product_types` VALUES ('729', '1', '729', 'Artificial Blueberry Muffin Mi');
INSERT INTO `a_languages_a_product_types` VALUES ('730', '1', '730', 'KRAFT');
INSERT INTO `a_languages_a_product_types` VALUES ('731', '1', '731', 'GEORGE WESTON BAKERIES');
INSERT INTO `a_languages_a_product_types` VALUES ('732', '1', '732', 'KEEBLER');
INSERT INTO `a_languages_a_product_types` VALUES ('733', '1', '733', 'CONTINENTAL MILLS');
INSERT INTO `a_languages_a_product_types` VALUES ('734', '1', '734', 'MCKEE BAKING');
INSERT INTO `a_languages_a_product_types` VALUES ('735', '1', '735', 'MARTHA WHITE FOODS');
INSERT INTO `a_languages_a_product_types` VALUES ('736', '1', '736', 'MISSION FOODS');
INSERT INTO `a_languages_a_product_types` VALUES ('737', '1', '737', 'NABISCO');
INSERT INTO `a_languages_a_product_types` VALUES ('738', '1', '738', 'PILLSBURY');
INSERT INTO `a_languages_a_product_types` VALUES ('739', '1', '739', 'PILLSBURY GRANDS');
INSERT INTO `a_languages_a_product_types` VALUES ('740', '1', '740', 'PILLSBURY Golden Layer Butterm');
INSERT INTO `a_languages_a_product_types` VALUES ('741', '1', '741', 'KRAFT FOODS');
INSERT INTO `a_languages_a_product_types` VALUES ('742', '1', '742', 'HEINZ');
INSERT INTO `a_languages_a_product_types` VALUES ('743', '1', '743', 'INTERSTATE BRANDS CORP');
INSERT INTO `a_languages_a_product_types` VALUES ('744', '1', '744', 'GENERAL MILLS');
INSERT INTO `a_languages_a_product_types` VALUES ('745', '1', '745', 'Waffle');
INSERT INTO `a_languages_a_product_types` VALUES ('746', '1', '746', 'Muffin');
INSERT INTO `a_languages_a_product_types` VALUES ('747', '1', '747', 'Tostada shells');
INSERT INTO `a_languages_a_product_types` VALUES ('748', '1', '748', 'Keikitos (muffins)');
INSERT INTO `a_languages_a_product_types` VALUES ('749', '1', '749', 'Pan Dulce');
INSERT INTO `a_languages_a_product_types` VALUES ('750', '1', '750', 'Pastry');
INSERT INTO `a_languages_a_product_types` VALUES ('751', '1', '751', 'Snacks');
INSERT INTO `a_languages_a_product_types` VALUES ('752', '1', '752', 'Candies');
INSERT INTO `a_languages_a_product_types` VALUES ('753', '1', '753', 'Baking chocolate');
INSERT INTO `a_languages_a_product_types` VALUES ('754', '1', '754', 'Ice creams');
INSERT INTO `a_languages_a_product_types` VALUES ('755', '1', '755', 'Desserts');
INSERT INTO `a_languages_a_product_types` VALUES ('756', '1', '756', 'Sherbet');
INSERT INTO `a_languages_a_product_types` VALUES ('757', '1', '757', 'Syrups');
INSERT INTO `a_languages_a_product_types` VALUES ('758', '1', '758', 'Puddings');
INSERT INTO `a_languages_a_product_types` VALUES ('759', '1', '759', 'Chocolate-flavored hazelnut sp');
INSERT INTO `a_languages_a_product_types` VALUES ('760', '1', '760', 'Toppings');
INSERT INTO `a_languages_a_product_types` VALUES ('761', '1', '761', 'Chewing gum');
INSERT INTO `a_languages_a_product_types` VALUES ('762', '1', '762', 'Cocoa');
INSERT INTO `a_languages_a_product_types` VALUES ('763', '1', '763', 'Egg custards');
INSERT INTO `a_languages_a_product_types` VALUES ('764', '1', '764', 'Gelatin desserts');
INSERT INTO `a_languages_a_product_types` VALUES ('765', '1', '765', 'Gelatins');
INSERT INTO `a_languages_a_product_types` VALUES ('766', '1', '766', 'Flan');
INSERT INTO `a_languages_a_product_types` VALUES ('767', '1', '767', 'Rennin');
INSERT INTO `a_languages_a_product_types` VALUES ('768', '1', '768', 'Frozen novelties');
INSERT INTO `a_languages_a_product_types` VALUES ('769', '1', '769', 'Frostings');
INSERT INTO `a_languages_a_product_types` VALUES ('770', '1', '770', 'Frozen yogurts');
INSERT INTO `a_languages_a_product_types` VALUES ('771', '1', '771', 'Fruit butters');
INSERT INTO `a_languages_a_product_types` VALUES ('772', '1', '772', 'Honey');
INSERT INTO `a_languages_a_product_types` VALUES ('773', '1', '773', 'Jams and preserves');
INSERT INTO `a_languages_a_product_types` VALUES ('774', '1', '774', 'Jellies');
INSERT INTO `a_languages_a_product_types` VALUES ('775', '1', '775', 'Marmalade');
INSERT INTO `a_languages_a_product_types` VALUES ('776', '1', '776', 'Molasses');
INSERT INTO `a_languages_a_product_types` VALUES ('777', '1', '777', 'Pectin');
INSERT INTO `a_languages_a_product_types` VALUES ('778', '1', '778', 'Pie fillings');
INSERT INTO `a_languages_a_product_types` VALUES ('779', '1', '779', 'Pudding');
INSERT INTO `a_languages_a_product_types` VALUES ('780', '1', '780', 'Sugars');
INSERT INTO `a_languages_a_product_types` VALUES ('781', '1', '781', 'Sweeteners');
INSERT INTO `a_languages_a_product_types` VALUES ('782', '1', '782', 'Snack');
INSERT INTO `a_languages_a_product_types` VALUES ('783', '1', '783', 'Tortilla chips');
INSERT INTO `a_languages_a_product_types` VALUES ('784', '1', '784', 'Cheese puffs and twists');
INSERT INTO `a_languages_a_product_types` VALUES ('785', '1', '785', 'Popcorn');
INSERT INTO `a_languages_a_product_types` VALUES ('786', '1', '786', 'Potato chips');
INSERT INTO `a_languages_a_product_types` VALUES ('787', '1', '787', 'Chocolate');
INSERT INTO `a_languages_a_product_types` VALUES ('788', '1', '788', 'Sugar');
INSERT INTO `a_languages_a_product_types` VALUES ('789', '1', '789', 'Amaranth');
INSERT INTO `a_languages_a_product_types` VALUES ('790', '1', '790', 'Amaranth grain');
INSERT INTO `a_languages_a_product_types` VALUES ('791', '1', '791', 'Arrowroot flour');
INSERT INTO `a_languages_a_product_types` VALUES ('792', '1', '792', 'Barley');
INSERT INTO `a_languages_a_product_types` VALUES ('793', '1', '793', 'Buckwheat');
INSERT INTO `a_languages_a_product_types` VALUES ('794', '1', '794', 'Buckwheat groats');
INSERT INTO `a_languages_a_product_types` VALUES ('795', '1', '795', 'Buckwheat flour');
INSERT INTO `a_languages_a_product_types` VALUES ('796', '1', '796', 'Bulgur');
INSERT INTO `a_languages_a_product_types` VALUES ('797', '1', '797', 'Corn bran');
INSERT INTO `a_languages_a_product_types` VALUES ('798', '1', '798', 'Corn flour');
INSERT INTO `a_languages_a_product_types` VALUES ('799', '1', '799', 'Cornmeal');
INSERT INTO `a_languages_a_product_types` VALUES ('800', '1', '800', 'Cornstarch');
INSERT INTO `a_languages_a_product_types` VALUES ('801', '1', '801', 'Couscous');
INSERT INTO `a_languages_a_product_types` VALUES ('802', '1', '802', 'Hominy');
INSERT INTO `a_languages_a_product_types` VALUES ('803', '1', '803', 'Millet');
INSERT INTO `a_languages_a_product_types` VALUES ('804', '1', '804', 'Oat bran');
INSERT INTO `a_languages_a_product_types` VALUES ('805', '1', '805', 'Quinoa');
INSERT INTO `a_languages_a_product_types` VALUES ('806', '1', '806', 'Rice');
INSERT INTO `a_languages_a_product_types` VALUES ('807', '1', '807', 'Oats');
INSERT INTO `a_languages_a_product_types` VALUES ('808', '1', '808', 'Rice bran');
INSERT INTO `a_languages_a_product_types` VALUES ('809', '1', '809', 'Rice flour');
INSERT INTO `a_languages_a_product_types` VALUES ('810', '1', '810', 'Rye');
INSERT INTO `a_languages_a_product_types` VALUES ('811', '1', '811', 'Rye flour');
INSERT INTO `a_languages_a_product_types` VALUES ('812', '1', '812', 'Semolina');
INSERT INTO `a_languages_a_product_types` VALUES ('813', '1', '813', 'Sorghum');
INSERT INTO `a_languages_a_product_types` VALUES ('814', '1', '814', 'Tapioca');
INSERT INTO `a_languages_a_product_types` VALUES ('815', '1', '815', 'Triticale');
INSERT INTO `a_languages_a_product_types` VALUES ('816', '1', '816', 'Triticale flour');
INSERT INTO `a_languages_a_product_types` VALUES ('817', '1', '817', 'Wheat');
INSERT INTO `a_languages_a_product_types` VALUES ('818', '1', '818', 'Wheat bran');
INSERT INTO `a_languages_a_product_types` VALUES ('819', '1', '819', 'Wheat germ');
INSERT INTO `a_languages_a_product_types` VALUES ('820', '1', '820', 'Wheat flour');
INSERT INTO `a_languages_a_product_types` VALUES ('821', '1', '821', 'Wild rice');
INSERT INTO `a_languages_a_product_types` VALUES ('822', '1', '822', 'Pasta');
INSERT INTO `a_languages_a_product_types` VALUES ('823', '1', '823', 'Macaroni');
INSERT INTO `a_languages_a_product_types` VALUES ('824', '1', '824', 'Spaghetti');
INSERT INTO `a_languages_a_product_types` VALUES ('825', '1', '825', 'Wheat flours');
INSERT INTO `a_languages_a_product_types` VALUES ('826', '1', '826', 'Barley flour or meal');
INSERT INTO `a_languages_a_product_types` VALUES ('827', '1', '827', 'Barley malt flour');
INSERT INTO `a_languages_a_product_types` VALUES ('828', '1', '828', 'Oat flour');
INSERT INTO `a_languages_a_product_types` VALUES ('829', '1', '829', 'Rice noodles');
INSERT INTO `a_languages_a_product_types` VALUES ('830', '1', '830', 'Kamut');
INSERT INTO `a_languages_a_product_types` VALUES ('831', '1', '831', 'Spelt');
INSERT INTO `a_languages_a_product_types` VALUES ('832', '1', '832', 'Teff');
INSERT INTO `a_languages_a_product_types` VALUES ('833', '1', '833', 'Millet flour');
INSERT INTO `a_languages_a_product_types` VALUES ('834', '1', '834', 'Sorghum flour');
INSERT INTO `a_languages_a_product_types` VALUES ('835', '1', '835', 'Fast foods');
INSERT INTO `a_languages_a_product_types` VALUES ('836', '1', '836', 'Entrees');
INSERT INTO `a_languages_a_product_types` VALUES ('837', '1', '837', 'Tostada with guacamole');
INSERT INTO `a_languages_a_product_types` VALUES ('838', '1', '838', 'Sandwiches and burgers');
INSERT INTO `a_languages_a_product_types` VALUES ('839', '1', '839', 'Side dishes');
INSERT INTO `a_languages_a_product_types` VALUES ('840', '1', '840', 'BURGER KING');
INSERT INTO `a_languages_a_product_types` VALUES ('841', '1', '841', 'Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('842', '1', '842', 'McDONALD\'S');
INSERT INTO `a_languages_a_product_types` VALUES ('843', '1', '843', 'WENDY\'S');
INSERT INTO `a_languages_a_product_types` VALUES ('844', '1', '844', 'TACO BELL');
INSERT INTO `a_languages_a_product_types` VALUES ('845', '1', '845', 'PIZZA HUT 12\" Cheese Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('846', '1', '846', 'PIZZA HUT 12\" Pepperoni Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('847', '1', '847', 'PIZZA HUT 12\" Super Supreme Pi');
INSERT INTO `a_languages_a_product_types` VALUES ('848', '1', '848', 'DOMINO\'S 14\" Cheese Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('849', '1', '849', 'DOMINO\'S 14\" Pepperoni Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('850', '1', '850', 'DOMINO\'S 14\" EXTRAVAGANZZA FEA');
INSERT INTO `a_languages_a_product_types` VALUES ('851', '1', '851', 'PAPA JOHN\'S 14\" Cheese Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('852', '1', '852', 'PAPA JOHN\'S 14\" Pepperoni Pizz');
INSERT INTO `a_languages_a_product_types` VALUES ('853', '1', '853', 'PAPA JOHN\'S 14\" The Works Pizz');
INSERT INTO `a_languages_a_product_types` VALUES ('854', '1', '854', 'LITTLE CAESARS 14\" Original Ro');
INSERT INTO `a_languages_a_product_types` VALUES ('855', '1', '855', 'LITTLE CAESARS 14\" Original Ro');
INSERT INTO `a_languages_a_product_types` VALUES ('856', '1', '856', 'LITTLE CAESARS 14\" Original Ro');
INSERT INTO `a_languages_a_product_types` VALUES ('857', '1', '857', 'LITTLE CAESARS 14\" Cheese Pizz');
INSERT INTO `a_languages_a_product_types` VALUES ('858', '1', '858', 'LITTLE CAESARS 14\" Pepperoni P');
INSERT INTO `a_languages_a_product_types` VALUES ('859', '1', '859', 'LITTLE CAESARS 14\" Cheese Pizz');
INSERT INTO `a_languages_a_product_types` VALUES ('860', '1', '860', 'PIZZA HUT 14\" Cheese Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('861', '1', '861', 'PIZZA HUT 14\" Pepperoni Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('862', '1', '862', 'PIZZA HUT 14\" Super Supreme Pi');
INSERT INTO `a_languages_a_product_types` VALUES ('863', '1', '863', 'Fast Food');
INSERT INTO `a_languages_a_product_types` VALUES ('864', '1', '864', 'McDONALD\'S Bacon Ranch Salad w');
INSERT INTO `a_languages_a_product_types` VALUES ('865', '1', '865', 'Light Ice Cream');
INSERT INTO `a_languages_a_product_types` VALUES ('866', '1', '866', 'POPEYES');
INSERT INTO `a_languages_a_product_types` VALUES ('867', '1', '867', 'KENTUCKY FRIED CHICKEN');
INSERT INTO `a_languages_a_product_types` VALUES ('868', '1', '868', 'Yogurt parfait');
INSERT INTO `a_languages_a_product_types` VALUES ('869', '1', '869', 'DIGIORNO Pizza');
INSERT INTO `a_languages_a_product_types` VALUES ('870', '1', '870', 'MORNINGSTAR FARMS Garden Veggi');
INSERT INTO `a_languages_a_product_types` VALUES ('871', '1', '871', 'MORNINGSTAR FARMS Grillers Bur');
INSERT INTO `a_languages_a_product_types` VALUES ('872', '1', '872', 'MORNINGSTAR FARMS Grillers Veg');
INSERT INTO `a_languages_a_product_types` VALUES ('873', '1', '873', 'MORNINGSTAR FARMS Veggie Break');
INSERT INTO `a_languages_a_product_types` VALUES ('874', '1', '874', 'MORNINGSTAR FARMS Spicy Black ');
INSERT INTO `a_languages_a_product_types` VALUES ('875', '1', '875', 'GREEN GIANT');
INSERT INTO `a_languages_a_product_types` VALUES ('876', '1', '876', 'LOMA LINDA Big Franks');
INSERT INTO `a_languages_a_product_types` VALUES ('877', '1', '877', 'Macaroni and Cheese');
INSERT INTO `a_languages_a_product_types` VALUES ('878', '1', '878', 'Spaghetti with meat sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('879', '1', '879', 'Pasta with Sliced Franks in To');
INSERT INTO `a_languages_a_product_types` VALUES ('880', '1', '880', 'Turkey Pot Pie');
INSERT INTO `a_languages_a_product_types` VALUES ('881', '1', '881', 'Beef Pot Pie');
INSERT INTO `a_languages_a_product_types` VALUES ('882', '1', '882', 'HOT POCKETS');
INSERT INTO `a_languages_a_product_types` VALUES ('883', '1', '883', 'HOT POCKETS Ham \'N Cheese Stuf');
INSERT INTO `a_languages_a_product_types` VALUES ('884', '1', '884', 'Tortellini');
INSERT INTO `a_languages_a_product_types` VALUES ('885', '1', '885', 'Chili con carne with beans');
INSERT INTO `a_languages_a_product_types` VALUES ('886', '1', '886', 'Beef stew');
INSERT INTO `a_languages_a_product_types` VALUES ('887', '1', '887', 'Chicken pot pie');
INSERT INTO `a_languages_a_product_types` VALUES ('888', '1', '888', 'Pasta with meatballs in tomato');
INSERT INTO `a_languages_a_product_types` VALUES ('889', '1', '889', 'Lasagna');
INSERT INTO `a_languages_a_product_types` VALUES ('890', '1', '890', 'Chili');
INSERT INTO `a_languages_a_product_types` VALUES ('891', '1', '891', 'Pasta with tomato sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('892', '1', '892', 'Lasagna with meat & sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('893', '1', '893', 'Burrito');
INSERT INTO `a_languages_a_product_types` VALUES ('894', '1', '894', 'Egg rolls');
INSERT INTO `a_languages_a_product_types` VALUES ('895', '1', '895', 'Rice bowl with chicken');
INSERT INTO `a_languages_a_product_types` VALUES ('896', '1', '896', 'Macaroni and cheese dinner wit');
INSERT INTO `a_languages_a_product_types` VALUES ('897', '1', '897', 'Macaroni and cheese dinner wit');
INSERT INTO `a_languages_a_product_types` VALUES ('898', '1', '898', 'LEAN POCKETS');
INSERT INTO `a_languages_a_product_types` VALUES ('899', '1', '899', 'Formulated bar');
INSERT INTO `a_languages_a_product_types` VALUES ('900', '1', '900', 'Pretzels');
INSERT INTO `a_languages_a_product_types` VALUES ('901', '1', '901', 'Campbell\'s V8 100% Vegetable J');
INSERT INTO `a_languages_a_product_types` VALUES ('902', '1', '902', 'Agutuk');
INSERT INTO `a_languages_a_product_types` VALUES ('903', '1', '903', 'Ascidians (tunughnak) (Alaska ');
INSERT INTO `a_languages_a_product_types` VALUES ('904', '1', '904', 'Bear');
INSERT INTO `a_languages_a_product_types` VALUES ('905', '1', '905', 'Whale');
INSERT INTO `a_languages_a_product_types` VALUES ('906', '1', '906', 'Caribou');
INSERT INTO `a_languages_a_product_types` VALUES ('907', '1', '907', 'Stew/soup');
INSERT INTO `a_languages_a_product_types` VALUES ('908', '1', '908', 'Chiton');
INSERT INTO `a_languages_a_product_types` VALUES ('909', '1', '909', 'Cloudberries');
INSERT INTO `a_languages_a_product_types` VALUES ('910', '1', '910', 'Cockles');
INSERT INTO `a_languages_a_product_types` VALUES ('911', '1', '911', 'Cranberry');
INSERT INTO `a_languages_a_product_types` VALUES ('912', '1', '912', 'Huckleberries');
INSERT INTO `a_languages_a_product_types` VALUES ('913', '1', '913', 'Stew');
INSERT INTO `a_languages_a_product_types` VALUES ('914', '1', '914', 'Moose');
INSERT INTO `a_languages_a_product_types` VALUES ('915', '1', '915', 'Mashu roots');
INSERT INTO `a_languages_a_product_types` VALUES ('916', '1', '916', 'Mouse nuts');
INSERT INTO `a_languages_a_product_types` VALUES ('917', '1', '917', 'Octopus (Alaska Native)');
INSERT INTO `a_languages_a_product_types` VALUES ('918', '1', '918', 'Seal');
INSERT INTO `a_languages_a_product_types` VALUES ('919', '1', '919', 'Oopah (tunicate)');
INSERT INTO `a_languages_a_product_types` VALUES ('920', '1', '920', 'Owl');
INSERT INTO `a_languages_a_product_types` VALUES ('921', '1', '921', 'Sea cucumber');
INSERT INTO `a_languages_a_product_types` VALUES ('922', '1', '922', 'Sourdock');
INSERT INTO `a_languages_a_product_types` VALUES ('923', '1', '923', 'Squirrel');
INSERT INTO `a_languages_a_product_types` VALUES ('924', '1', '924', 'Walrus');
INSERT INTO `a_languages_a_product_types` VALUES ('925', '1', '925', 'Deer (venison)');
INSERT INTO `a_languages_a_product_types` VALUES ('926', '1', '926', 'Willow');
INSERT INTO `a_languages_a_product_types` VALUES ('927', '1', '927', 'Mush');
INSERT INTO `a_languages_a_product_types` VALUES ('928', '1', '928', 'Melon');
INSERT INTO `a_languages_a_product_types` VALUES ('929', '1', '929', 'Chilchen (Red Berry Beverage) ');
INSERT INTO `a_languages_a_product_types` VALUES ('930', '1', '930', 'Mutton');
INSERT INTO `a_languages_a_product_types` VALUES ('931', '1', '931', 'Frybread');
INSERT INTO `a_languages_a_product_types` VALUES ('932', '1', '932', 'Tortilla');
INSERT INTO `a_languages_a_product_types` VALUES ('933', '1', '933', 'Tamales (Navajo)');
INSERT INTO `a_languages_a_product_types` VALUES ('934', '1', '934', 'Salmonberries');
INSERT INTO `a_languages_a_product_types` VALUES ('935', '1', '935', 'Elk');
INSERT INTO `a_languages_a_product_types` VALUES ('936', '1', '936', 'Buffalo');
INSERT INTO `a_languages_a_product_types` VALUES ('937', '1', '937', 'Chokecherries');
INSERT INTO `a_languages_a_product_types` VALUES ('938', '1', '938', 'Steelhead trout');
INSERT INTO `a_languages_a_product_types` VALUES ('939', '1', '939', 'Acorn stew (Apache)');
INSERT INTO `a_languages_a_product_types` VALUES ('940', '1', '940', 'Smelt');
INSERT INTO `a_languages_a_product_types` VALUES ('941', '1', '941', 'Corned beef and potatoes in to');
INSERT INTO `a_languages_a_product_types` VALUES ('942', '1', '942', 'Tennis Bread');
INSERT INTO `a_languages_a_product_types` VALUES ('943', '1', '943', 'Salmon');
INSERT INTO `a_languages_a_product_types` VALUES ('944', '1', '944', 'Agave');
INSERT INTO `a_languages_a_product_types` VALUES ('945', '1', '945', 'Cattail');
INSERT INTO `a_languages_a_product_types` VALUES ('946', '1', '946', 'Plains Pricklypear');
INSERT INTO `a_languages_a_product_types` VALUES ('947', '1', '947', 'Prairie Turnips');
INSERT INTO `a_languages_a_product_types` VALUES ('948', '1', '948', 'Rose Hips');
INSERT INTO `a_languages_a_product_types` VALUES ('949', '1', '949', 'Stinging Nettles');
INSERT INTO `a_languages_a_product_types` VALUES ('950', '1', '950', 'Pinon Nuts');
INSERT INTO `a_languages_a_product_types` VALUES ('951', '1', '951', 'Sea lion');
INSERT INTO `a_languages_a_product_types` VALUES ('952', '1', '952', 'Yellow pond lily');
INSERT INTO `a_languages_a_product_types` VALUES ('953', '1', '953', 'Hazelnuts');
INSERT INTO `a_languages_a_product_types` VALUES ('954', '1', '954', 'Piki bread');
INSERT INTO `a_languages_a_product_types` VALUES ('955', '1', '955', 'Tamales');
INSERT INTO `a_languages_a_product_types` VALUES ('956', '1', '956', 'APPLEBEE\'S');
INSERT INTO `a_languages_a_product_types` VALUES ('957', '1', '957', 'T.G.I. FRIDAY\'S');
INSERT INTO `a_languages_a_product_types` VALUES ('958', '1', '958', 'Restaurant');
INSERT INTO `a_languages_a_product_types` VALUES ('959', '1', '959', 'CRACKER BARREL');
INSERT INTO `a_languages_a_product_types` VALUES ('960', '1', '960', 'DENNY\'S');
INSERT INTO `a_languages_a_product_types` VALUES ('961', '1', '961', 'Fruit-flavored drink');
INSERT INTO `a_languages_a_product_types` VALUES ('962', '1', '962', 'Creamy dressing');
INSERT INTO `a_languages_a_product_types` VALUES ('963', '1', '963', 'Imitation cheese');
INSERT INTO `a_languages_a_product_types` VALUES ('964', '1', '964', 'Turkey bacon');
INSERT INTO `a_languages_a_product_types` VALUES ('965', '1', '965', 'Milk dessert');
INSERT INTO `a_languages_a_product_types` VALUES ('966', '1', '966', 'Whipped topping');
INSERT INTO `a_languages_a_product_types` VALUES ('967', '1', '967', 'Mayonnaise');
INSERT INTO `a_languages_a_product_types` VALUES ('968', '1', '968', 'Granola bar');
INSERT INTO `a_languages_a_product_types` VALUES ('969', '1', '969', 'Orange-strawberry-banana juice');
INSERT INTO `a_languages_a_product_types` VALUES ('970', '1', '970', 'Vegetable oil-butter spread');
INSERT INTO `a_languages_a_product_types` VALUES ('971', '1', '971', 'Turkey and pork sausage');
INSERT INTO `a_languages_a_product_types` VALUES ('972', '1', '972', 'Corn beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('973', '1', '973', 'Bean beverage');
INSERT INTO `a_languages_a_product_types` VALUES ('974', '1', '974', 'Pork sausage rice links');
INSERT INTO `a_languages_a_product_types` VALUES ('975', '1', '975', 'Papad');
INSERT INTO `a_languages_a_product_types` VALUES ('976', '1', '976', 'Rice cake');
INSERT INTO `a_languages_a_product_types` VALUES ('977', '1', '977', 'Orange juice drink');
INSERT INTO `a_languages_a_product_types` VALUES ('978', '1', '978', 'Fluid replacement');
INSERT INTO `a_languages_a_product_types` VALUES ('979', '1', '979', 'Breakfast bars');
INSERT INTO `a_languages_a_product_types` VALUES ('980', '1', '980', 'Vermicelli');
INSERT INTO `a_languages_a_product_types` VALUES ('981', '1', '981', 'Fish sticks');
INSERT INTO `a_languages_a_product_types` VALUES ('982', '1', '982', 'Luncheon slices');
INSERT INTO `a_languages_a_product_types` VALUES ('983', '1', '983', 'Meatballs');
INSERT INTO `a_languages_a_product_types` VALUES ('984', '1', '984', 'Vegetarian fillets');
INSERT INTO `a_languages_a_product_types` VALUES ('985', '1', '985', 'Vegetarian stew');
INSERT INTO `a_languages_a_product_types` VALUES ('986', '1', '986', 'Vegetarian meatloaf or patties');
INSERT INTO `a_languages_a_product_types` VALUES ('987', '1', '987', 'Bacon bits');
INSERT INTO `a_languages_a_product_types` VALUES ('988', '1', '988', 'Butter replacement');
INSERT INTO `a_languages_a_product_types` VALUES ('989', '1', '989', 'Tomato sauce');
INSERT INTO `a_languages_a_product_types` VALUES ('990', '1', '990', 'Whipped cream substitute');
INSERT INTO `a_languages_a_product_types` VALUES ('991', '1', '991', 'Eggs');
INSERT INTO `a_languages_a_product_types` VALUES ('992', '1', '992', 'Dove');
INSERT INTO `a_languages_a_product_types` VALUES ('993', '1', '993', 'Soybean');
INSERT INTO `a_languages_a_product_types` VALUES ('994', '1', '994', 'Coffee and cocoa (mocha) powde');
INSERT INTO `a_languages_a_product_types` VALUES ('995', '1', '995', 'Tomato and vegetable juice');
INSERT INTO `a_languages_a_product_types` VALUES ('996', '1', '996', 'Chocolate-flavored drink');
INSERT INTO `a_languages_a_product_types` VALUES ('997', '1', '997', 'Apple cider-flavored drink');
INSERT INTO `a_languages_a_product_types` VALUES ('998', '1', '998', 'Cranberry juice');
INSERT INTO `a_languages_a_product_types` VALUES ('999', '1', '999', 'Palm hearts');
INSERT INTO `a_languages_a_product_types` VALUES ('1000', '1', '1000', 'Yeast extract spread');
INSERT INTO `a_languages_a_product_types` VALUES ('1001', '1', '1001', 'Baked beans');
INSERT INTO `a_languages_a_product_types` VALUES ('1002', '1', '1002', 'Frozen novelites');
INSERT INTO `a_languages_a_product_types` VALUES ('1003', '1', '1003', 'Tofu yogurt');
INSERT INTO `a_languages_a_product_types` VALUES ('1004', '1', '1004', 'Jellyfish');
INSERT INTO `a_languages_a_product_types` VALUES ('1005', '1', '1005', 'Cereal ready-to-eat');
INSERT INTO `a_languages_a_product_types` VALUES ('1006', '1', '1006', 'Ensure plus');
INSERT INTO `a_languages_a_product_types` VALUES ('1007', '1', '1007', 'AMARANTH FLAKES');
INSERT INTO `a_languages_a_product_types` VALUES ('1008', '1', '1008', 'Breakfast bar');
INSERT INTO `a_languages_a_product_types` VALUES ('1009', '1', '1009', 'Mayonnaise dressing');
INSERT INTO `a_languages_a_product_types` VALUES ('1010', '1', '1010', 'Celery flakes');
INSERT INTO `a_languages_a_product_types` VALUES ('1011', '1', '1011', 'Cocktail mix');
INSERT INTO `a_languages_a_product_types` VALUES ('1012', '1', '1012', 'Fruit-flavored drink mix');
INSERT INTO `a_languages_a_product_types` VALUES ('1013', '1', '1013', 'Vital wheat gluten');
INSERT INTO `a_languages_a_product_types` VALUES ('1014', '1', '1014', 'Frog legs');
INSERT INTO `a_languages_a_product_types` VALUES ('1015', '1', '1015', 'Turtle');
